import { BigNumber } from "bignumber.js";

export const ZERO = new BigNumber(0);
export const ONE = new BigNumber(1);
export const CONTRACT_LABELS = {
  WETH: "WETH",
  DAI: "DAI",
  PULL_TOKEN: "PULL_TOKEN",
  SEND_TOKEN: "SEND_TOKEN",
  SET_APPROVAL: "SET_APPROVAL",
  DEPOSIT_IN_AAVE: "DEPOSIT_IN_AAVE",
  WITHDRAW_FROM_AAVE: "WITHDRAW_FROM_AAVE",
  BORROW_FROM_AAVE: "BORROW_FROM_AAVE",
  SWAP_ON_ONE_INCH: "SWAP_ON_ONE_INCH",
  TAKE_A_FLASHLOAN: "TAKE_A_FLASHLOAN",
  OPERATION_EXECUTOR: "OPERATION_EXECUTOR",
  OPERATION_STORAGE: "OPERATION_STORAGE",
  OPERATIONS_REGISTRY: "OPERATIONS_REGISTRY",
  FLASH_MINT_MODULE: "FLASH_MINT_MODULE",
  ONE_INCH_AGGREGATOR: "ONE_INCH_AGGREGATOR",
  AAVE_LENDING_POOL: "AAVE_LENDING_POOL",
  AAVE_WETH_GATEWAY: "AAVE_WETH_GATEWAY",
};
export const OPERATION_LABELS = {
  OPEN_AAVE_POSITION: "OPEN_AAVE_POSITION"
}
