import { BigNumber } from 'bignumber.js'

export const ZERO = new BigNumber(0)
export const ONE = new BigNumber(1)
export const TEN = new BigNumber(10)
export const MAX_UINT =
  '115792089237316195423570985008687907853269984665640564039457584007913129639935'

export const CONTRACT_LABELS = {
  common: {
    WETH: 'WETH',
    DAI: 'DAI',
    PULL_TOKEN: 'PULL_TOKEN',
    SEND_TOKEN: 'SEND_TOKEN',
    SET_APPROVAL: 'SET_APPROVAL',
    TAKE_A_FLASHLOAN: 'TAKE_A_FLASHLOAN',
    SWAP_ON_ONE_INCH: 'SWAP_ON_ONE_INCH',
    OPERATION_EXECUTOR: 'OPERATION_EXECUTOR',
    OPERATION_STORAGE: 'OPERATION_STORAGE',
    ONE_INCH_AGGREGATOR: 'ONE_INCH_AGGREGATOR',
    EXCHANGE: 'EXCHANGE',
  },
  aave: {
    DEPOSIT_IN_AAVE: 'DEPOSIT_IN_AAVE',
    WITHDRAW_FROM_AAVE: 'WITHDRAW_FROM_AAVE',
    BORROW_FROM_AAVE: 'BORROW_FROM_AAVE',
    AAVE_LENDING_POOL: 'AAVE_LENDING_POOL',
    AAVE_WETH_GATEWAY: 'AAVE_WETH_GATEWAY',
  },
  maker: {
    DEPOSIT: 'DEPOSIT',
    PAYBACK: 'PAYBACK',
    WITHDRAW: 'WITHDRAW',
    GENERATE: 'GENERATE',
    OPEN_VAULT: 'OPEN_VAULT',
    CDP_ALLOW: 'CDP_ALLOW',
    CDP_DISALLOW: 'CDP_DISALLOW',
    MCD_VIEW: 'MCD_VIEW',
    GUNI_VIEW: 'GUNI_VIEW',
    FLASH_MINT_MODULE: 'FLASH_MINT_MODULE',
  },
  guni: {
    GUNI_DEPOSIT: 'GUNI_DEPOSIT',
    GUNI_WITHDRAW: 'GUNI_WITHDRAW',
  },
  test: {
    DUMMY_EXCHANGE: 'DUMMY_EXCHANGE',
    DUMMY_SWAP: 'DUMMY_SWAP',
  }
}
