"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.aaveOpenV3OperationDefinition = exports.aaveCloseV3OperationDefinition = exports.aaveOpenV2OperationDefinition = exports.aaveCloseV2OperationDefinition = void 0;
var close_1 = require("./aave/v2/close");
Object.defineProperty(exports, "aaveCloseV2OperationDefinition", { enumerable: true, get: function () { return close_1.aaveCloseV2OperationDefinition; } });
var open_1 = require("./aave/v2/open");
Object.defineProperty(exports, "aaveOpenV2OperationDefinition", { enumerable: true, get: function () { return open_1.aaveOpenV2OperationDefinition; } });
var close_2 = require("./aave/v3/close");
Object.defineProperty(exports, "aaveCloseV3OperationDefinition", { enumerable: true, get: function () { return close_2.aaveCloseV3OperationDefinition; } });
var open_2 = require("./aave/v3/open");
Object.defineProperty(exports, "aaveOpenV3OperationDefinition", { enumerable: true, get: function () { return open_2.aaveOpenV3OperationDefinition; } });
