export const correlatedAssetDictionary = {
  CorrelatedAssetFee: {
    ETH: [
      'WETH',
      'ETH',
      'WSTETH',
      'CBETH',
      'RETH',
      'STETH',
      'OSETH',
      'WEETH',
      'EZETH',
      'AWSTETH',
      'ASETH',
      'CWETHV3',
    ], // ETH correlated assets
    BTC: ['WBTC', 'TBTC'], // BTC correlated assets
    Stable: ['USDC', 'DAI', 'GHO', 'SDAI', 'USDT', 'CDAI', 'AUSDC', 'PYUSD'], // USDC correlated assets
  },
  LowCorrelatedAssetFee: {
    ETH: [
      'WSTETH',
      'RETH',
      'CBETH',
      'STETH',
      'AETHWSTETH',
      'AETHWETH',
      'AETHRETH',
      'AETHCBETH',
      'ASETH',
      'AWETH',
      'CETH',
      'CWETHV3',
      'WEETH',
      'WETH',
    ],
    BTC: ['WBTC', 'TBTC', 'AWBTC', 'AETHWBTC'],
    Stable: [
      'DAI',
      'USDT',
      'USDC',
      'PYUSD',
      'FRAX',
      'LUSD',
      'GUSD',
      'CRVUSD',
      'SDAI',
      'SUSDE',
      'USDE',
      'AETHSDAI',
      'AETHUSDC',
      'AETHUSDT',
      'AETHDAI',
      'AETHPYUSD',
      'AETHLUSD',
      'AUSDC',
      'ADAI',
      'AUSDT',
      'CUSDCV3',
      'CDAI',
      'CUSDC',
      'SUSD',
      'USDC.E',
    ],
  },
}
