/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../../../../common";

export interface IPoolTakerActionsInterface extends Interface {
  getFunction(
    nameOrSignature: "bucketTake" | "take" | "takeReserves"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "bucketTake",
    values: [AddressLike, boolean, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "take",
    values: [AddressLike, BigNumberish, AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "takeReserves",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "bucketTake", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "take", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "takeReserves",
    data: BytesLike
  ): Result;
}

export interface IPoolTakerActions extends BaseContract {
  connect(runner?: ContractRunner | null): IPoolTakerActions;
  waitForDeployment(): Promise<this>;

  interface: IPoolTakerActionsInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  bucketTake: TypedContractMethod<
    [
      borrowerAddress_: AddressLike,
      depositTake_: boolean,
      index_: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  take: TypedContractMethod<
    [
      borrowerAddress_: AddressLike,
      maxAmount_: BigNumberish,
      callee_: AddressLike,
      data_: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  takeReserves: TypedContractMethod<
    [maxAmount_: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "bucketTake"
  ): TypedContractMethod<
    [
      borrowerAddress_: AddressLike,
      depositTake_: boolean,
      index_: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "take"
  ): TypedContractMethod<
    [
      borrowerAddress_: AddressLike,
      maxAmount_: BigNumberish,
      callee_: AddressLike,
      data_: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "takeReserves"
  ): TypedContractMethod<[maxAmount_: BigNumberish], [bigint], "nonpayable">;

  filters: {};
}
