/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../../../../common";

export interface IPoolImmutablesInterface extends utils.Interface {
  functions: {
    "collateralAddress()": FunctionFragment;
    "poolType()": FunctionFragment;
    "quoteTokenAddress()": FunctionFragment;
    "quoteTokenScale()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "collateralAddress"
      | "poolType"
      | "quoteTokenAddress"
      | "quoteTokenScale"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "collateralAddress",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "poolType", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "quoteTokenAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "quoteTokenScale",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "collateralAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "poolType", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "quoteTokenAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "quoteTokenScale",
    data: BytesLike
  ): Result;

  events: {};
}

export interface IPoolImmutables extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IPoolImmutablesInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    collateralAddress(overrides?: CallOverrides): Promise<[string]>;

    poolType(overrides?: CallOverrides): Promise<[number]>;

    quoteTokenAddress(overrides?: CallOverrides): Promise<[string]>;

    quoteTokenScale(overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  collateralAddress(overrides?: CallOverrides): Promise<string>;

  poolType(overrides?: CallOverrides): Promise<number>;

  quoteTokenAddress(overrides?: CallOverrides): Promise<string>;

  quoteTokenScale(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    collateralAddress(overrides?: CallOverrides): Promise<string>;

    poolType(overrides?: CallOverrides): Promise<number>;

    quoteTokenAddress(overrides?: CallOverrides): Promise<string>;

    quoteTokenScale(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    collateralAddress(overrides?: CallOverrides): Promise<BigNumber>;

    poolType(overrides?: CallOverrides): Promise<BigNumber>;

    quoteTokenAddress(overrides?: CallOverrides): Promise<BigNumber>;

    quoteTokenScale(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    collateralAddress(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    poolType(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    quoteTokenAddress(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    quoteTokenScale(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
