/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IERC20PoolImmutables,
  IERC20PoolImmutablesInterface,
} from "../../../../../../../system/contracts/ajna/interfaces/pool/erc20/IERC20PoolImmutables";

const _abi = [
  {
    inputs: [],
    name: "collateralScale",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IERC20PoolImmutables__factory {
  static readonly abi = _abi;
  static createInterface(): IERC20PoolImmutablesInterface {
    return new utils.Interface(_abi) as IERC20PoolImmutablesInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IERC20PoolImmutables {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IERC20PoolImmutables;
  }
}
