/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { FlashBorrowerMock } from "./FlashBorrowerMock";
export type { IrmMock } from "./IrmMock";
export type { OracleMock } from "./OracleMock";
