/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IMorphoRepayCallback,
  IMorphoRepayCallbackInterface,
} from "../../../../../../system/contracts/interfaces/morpho-blue/IMorphoCallbacks.sol/IMorphoRepayCallback";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "assets",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "onMorphoRepay",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IMorphoRepayCallback__factory {
  static readonly abi = _abi;
  static createInterface(): IMorphoRepayCallbackInterface {
    return new utils.Interface(_abi) as IMorphoRepayCallbackInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IMorphoRepayCallback {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IMorphoRepayCallback;
  }
}
