/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IERC721Token,
  IERC721TokenInterface,
} from "../../../../../../../system/contracts/ajna/interfaces/pool/IPool.sol/IERC721Token";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "transferFrom",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IERC721Token__factory {
  static readonly abi = _abi;
  static createInterface(): IERC721TokenInterface {
    return new utils.Interface(_abi) as IERC721TokenInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IERC721Token {
    return new Contract(address, _abi, signerOrProvider) as IERC721Token;
  }
}
