/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../../common";

export interface IERC20PoolFactoryInterface extends utils.Interface {
  functions: {
    "deployPool(address,address,uint256)": FunctionFragment;
    "deployedPools(bytes32,address,address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "deployPool" | "deployedPools"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "deployPool",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "deployedPools",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<string>,
      PromiseOrValue<string>
    ]
  ): string;

  decodeFunctionResult(functionFragment: "deployPool", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "deployedPools",
    data: BytesLike
  ): Result;

  events: {};
}

export interface IERC20PoolFactory extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IERC20PoolFactoryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    deployPool(
      collateral_: PromiseOrValue<string>,
      quote_: PromiseOrValue<string>,
      interestRate_: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    deployedPools(
      nonSubsetHash: PromiseOrValue<BytesLike>,
      collateral_: PromiseOrValue<string>,
      quote_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[string]>;
  };

  deployPool(
    collateral_: PromiseOrValue<string>,
    quote_: PromiseOrValue<string>,
    interestRate_: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  deployedPools(
    nonSubsetHash: PromiseOrValue<BytesLike>,
    collateral_: PromiseOrValue<string>,
    quote_: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<string>;

  callStatic: {
    deployPool(
      collateral_: PromiseOrValue<string>,
      quote_: PromiseOrValue<string>,
      interestRate_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    deployedPools(
      nonSubsetHash: PromiseOrValue<BytesLike>,
      collateral_: PromiseOrValue<string>,
      quote_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {};

  estimateGas: {
    deployPool(
      collateral_: PromiseOrValue<string>,
      quote_: PromiseOrValue<string>,
      interestRate_: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    deployedPools(
      nonSubsetHash: PromiseOrValue<BytesLike>,
      collateral_: PromiseOrValue<string>,
      quote_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    deployPool(
      collateral_: PromiseOrValue<string>,
      quote_: PromiseOrValue<string>,
      interestRate_: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    deployedPools(
      nonSubsetHash: PromiseOrValue<BytesLike>,
      collateral_: PromiseOrValue<string>,
      quote_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
