/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IPoolFactory,
  IPoolFactoryInterface,
} from "../../../../../../system/contracts/ajna/interfaces/pool/IPoolFactory";

const _abi = [
  {
    inputs: [],
    name: "DecimalsNotCompliant",
    type: "error",
  },
  {
    inputs: [],
    name: "DeployQuoteCollateralSameToken",
    type: "error",
  },
  {
    inputs: [],
    name: "DeployWithZeroAddress",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "pool_",
        type: "address",
      },
    ],
    name: "PoolAlreadyExists",
    type: "error",
  },
  {
    inputs: [],
    name: "PoolInterestRateInvalid",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "pool_",
        type: "address",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "subsetHash_",
        type: "bytes32",
      },
    ],
    name: "PoolCreated",
    type: "event",
  },
] as const;

export class IPoolFactory__factory {
  static readonly abi = _abi;
  static createInterface(): IPoolFactoryInterface {
    return new utils.Interface(_abi) as IPoolFactoryInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IPoolFactory {
    return new Contract(address, _abi, signerOrProvider) as IPoolFactory;
  }
}
