/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../../../common";

export type DepositBorrowDataStruct = {
  quoteToken: AddressLike;
  collateralToken: AddressLike;
  depositAmount: BigNumberish;
  borrowAmount: BigNumberish;
  sumDepositAmounts: boolean;
  price: BigNumberish;
};

export type DepositBorrowDataStructOutput = [
  quoteToken: string,
  collateralToken: string,
  depositAmount: bigint,
  borrowAmount: bigint,
  sumDepositAmounts: boolean,
  price: bigint
] & {
  quoteToken: string;
  collateralToken: string;
  depositAmount: bigint;
  borrowAmount: bigint;
  sumDepositAmounts: boolean;
  price: bigint;
};

export interface AjnaDepositBorrowInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "erc20PoolFactory"
      | "execute"
      | "parseInputs"
      | "poolUtilsInfo"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "erc20PoolFactory",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "execute",
    values: [BytesLike, BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "parseInputs",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "poolUtilsInfo",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "erc20PoolFactory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "execute", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "parseInputs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "poolUtilsInfo",
    data: BytesLike
  ): Result;
}

export interface AjnaDepositBorrow extends BaseContract {
  connect(runner?: ContractRunner | null): AjnaDepositBorrow;
  waitForDeployment(): Promise<this>;

  interface: AjnaDepositBorrowInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  erc20PoolFactory: TypedContractMethod<[], [string], "view">;

  execute: TypedContractMethod<
    [data: BytesLike, paramsMap: BigNumberish[]],
    [void],
    "payable"
  >;

  parseInputs: TypedContractMethod<
    [_callData: BytesLike],
    [DepositBorrowDataStructOutput],
    "view"
  >;

  poolUtilsInfo: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "erc20PoolFactory"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "execute"
  ): TypedContractMethod<
    [data: BytesLike, paramsMap: BigNumberish[]],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "parseInputs"
  ): TypedContractMethod<
    [_callData: BytesLike],
    [DepositBorrowDataStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "poolUtilsInfo"
  ): TypedContractMethod<[], [string], "view">;

  filters: {};
}
