/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  AaveV3L2Payback,
  AaveV3L2PaybackInterface,
} from "../../../../../../../system/contracts/actions/aave/v3l2/Payback.sol/AaveV3L2Payback";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_registry",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
      {
        internalType: "uint8[]",
        name: "paramsMap",
        type: "uint8[]",
      },
    ],
    name: "execute",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "_callData",
        type: "bytes",
      },
    ],
    name: "parseInputs",
    outputs: [
      {
        components: [
          {
            internalType: "address",
            name: "asset",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "amount",
            type: "uint256",
          },
          {
            internalType: "bool",
            name: "paybackAll",
            type: "bool",
          },
        ],
        internalType: "struct PaybackData",
        name: "params",
        type: "tuple",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
] as const;

export class AaveV3L2Payback__factory {
  static readonly abi = _abi;
  static createInterface(): AaveV3L2PaybackInterface {
    return new Interface(_abi) as AaveV3L2PaybackInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): AaveV3L2Payback {
    return new Contract(address, _abi, runner) as unknown as AaveV3L2Payback;
  }
}
