/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IAccountGuard } from "./IAccountGuard";
export type { IAccountImplementation } from "./IAccountImplementation";
