/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../../common";

export type PositionCreatedDataStruct = {
  protocol: string;
  positionType: string;
  collateralToken: AddressLike;
  debtToken: AddressLike;
};

export type PositionCreatedDataStructOutput = [
  protocol: string,
  positionType: string,
  collateralToken: string,
  debtToken: string
] & {
  protocol: string;
  positionType: string;
  collateralToken: string;
  debtToken: string;
};

export interface PositionCreatedInterface extends Interface {
  getFunction(nameOrSignature: "execute" | "parseInputs"): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "CreatePosition"): EventFragment;

  encodeFunctionData(
    functionFragment: "execute",
    values: [BytesLike, BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "parseInputs",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "execute", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "parseInputs",
    data: BytesLike
  ): Result;
}

export namespace CreatePositionEvent {
  export type InputTuple = [
    proxyAddress: AddressLike,
    protocol: string,
    positionType: string,
    collateralToken: AddressLike,
    debtToken: AddressLike
  ];
  export type OutputTuple = [
    proxyAddress: string,
    protocol: string,
    positionType: string,
    collateralToken: string,
    debtToken: string
  ];
  export interface OutputObject {
    proxyAddress: string;
    protocol: string;
    positionType: string;
    collateralToken: string;
    debtToken: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PositionCreated extends BaseContract {
  connect(runner?: ContractRunner | null): PositionCreated;
  waitForDeployment(): Promise<this>;

  interface: PositionCreatedInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  execute: TypedContractMethod<
    [data: BytesLike, arg1: BigNumberish[]],
    [void],
    "payable"
  >;

  parseInputs: TypedContractMethod<
    [_callData: BytesLike],
    [PositionCreatedDataStructOutput],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "execute"
  ): TypedContractMethod<
    [data: BytesLike, arg1: BigNumberish[]],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "parseInputs"
  ): TypedContractMethod<
    [_callData: BytesLike],
    [PositionCreatedDataStructOutput],
    "view"
  >;

  getEvent(
    key: "CreatePosition"
  ): TypedContractEvent<
    CreatePositionEvent.InputTuple,
    CreatePositionEvent.OutputTuple,
    CreatePositionEvent.OutputObject
  >;

  filters: {
    "CreatePosition(address,string,string,address,address)": TypedContractEvent<
      CreatePositionEvent.InputTuple,
      CreatePositionEvent.OutputTuple,
      CreatePositionEvent.OutputObject
    >;
    CreatePosition: TypedContractEvent<
      CreatePositionEvent.InputTuple,
      CreatePositionEvent.OutputTuple,
      CreatePositionEvent.OutputObject
    >;
  };
}
