/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../../common";

export type PositionCreatedDataStruct = {
  protocol: PromiseOrValue<string>;
  positionType: PromiseOrValue<string>;
  collateralToken: PromiseOrValue<string>;
  debtToken: PromiseOrValue<string>;
};

export type PositionCreatedDataStructOutput = [
  string,
  string,
  string,
  string
] & {
  protocol: string;
  positionType: string;
  collateralToken: string;
  debtToken: string;
};

export interface PositionCreatedInterface extends utils.Interface {
  functions: {
    "execute(bytes,uint8[])": FunctionFragment;
    "parseInputs(bytes)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "execute" | "parseInputs"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "execute",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<BigNumberish>[]]
  ): string;
  encodeFunctionData(
    functionFragment: "parseInputs",
    values: [PromiseOrValue<BytesLike>]
  ): string;

  decodeFunctionResult(functionFragment: "execute", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "parseInputs",
    data: BytesLike
  ): Result;

  events: {
    "CreatePosition(address,string,string,address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "CreatePosition"): EventFragment;
}

export interface CreatePositionEventObject {
  proxyAddress: string;
  protocol: string;
  positionType: string;
  collateralToken: string;
  debtToken: string;
}
export type CreatePositionEvent = TypedEvent<
  [string, string, string, string, string],
  CreatePositionEventObject
>;

export type CreatePositionEventFilter = TypedEventFilter<CreatePositionEvent>;

export interface PositionCreated extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: PositionCreatedInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    execute(
      data: PromiseOrValue<BytesLike>,
      arg1: PromiseOrValue<BigNumberish>[],
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    parseInputs(
      _callData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<
      [PositionCreatedDataStructOutput] & {
        params: PositionCreatedDataStructOutput;
      }
    >;
  };

  execute(
    data: PromiseOrValue<BytesLike>,
    arg1: PromiseOrValue<BigNumberish>[],
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  parseInputs(
    _callData: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<PositionCreatedDataStructOutput>;

  callStatic: {
    execute(
      data: PromiseOrValue<BytesLike>,
      arg1: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<void>;

    parseInputs(
      _callData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PositionCreatedDataStructOutput>;
  };

  filters: {
    "CreatePosition(address,string,string,address,address)"(
      proxyAddress?: PromiseOrValue<string> | null,
      protocol?: null,
      positionType?: null,
      collateralToken?: null,
      debtToken?: null
    ): CreatePositionEventFilter;
    CreatePosition(
      proxyAddress?: PromiseOrValue<string> | null,
      protocol?: null,
      positionType?: null,
      collateralToken?: null,
      debtToken?: null
    ): CreatePositionEventFilter;
  };

  estimateGas: {
    execute(
      data: PromiseOrValue<BytesLike>,
      arg1: PromiseOrValue<BigNumberish>[],
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    parseInputs(
      _callData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    execute(
      data: PromiseOrValue<BytesLike>,
      arg1: PromiseOrValue<BigNumberish>[],
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    parseInputs(
      _callData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
