/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../../common";

export type SwapDataStruct = {
  fromAsset: PromiseOrValue<string>;
  toAsset: PromiseOrValue<string>;
  amount: PromiseOrValue<BigNumberish>;
  receiveAtLeast: PromiseOrValue<BigNumberish>;
  fee: PromiseOrValue<BigNumberish>;
  withData: PromiseOrValue<BytesLike>;
  collectFeeInFromToken: PromiseOrValue<boolean>;
};

export type SwapDataStructOutput = [
  string,
  string,
  BigNumber,
  BigNumber,
  BigNumber,
  string,
  boolean
] & {
  fromAsset: string;
  toAsset: string;
  amount: BigNumber;
  receiveAtLeast: BigNumber;
  fee: BigNumber;
  withData: string;
  collectFeeInFromToken: boolean;
};

export interface SwapActionInterface extends utils.Interface {
  functions: {
    "execute(bytes,uint8[])": FunctionFragment;
    "parseInputs(bytes)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "execute" | "parseInputs"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "execute",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<BigNumberish>[]]
  ): string;
  encodeFunctionData(
    functionFragment: "parseInputs",
    values: [PromiseOrValue<BytesLike>]
  ): string;

  decodeFunctionResult(functionFragment: "execute", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "parseInputs",
    data: BytesLike
  ): Result;

  events: {};
}

export interface SwapAction extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: SwapActionInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    execute(
      data: PromiseOrValue<BytesLike>,
      arg1: PromiseOrValue<BigNumberish>[],
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    parseInputs(
      _callData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[SwapDataStructOutput] & { params: SwapDataStructOutput }>;
  };

  execute(
    data: PromiseOrValue<BytesLike>,
    arg1: PromiseOrValue<BigNumberish>[],
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  parseInputs(
    _callData: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<SwapDataStructOutput>;

  callStatic: {
    execute(
      data: PromiseOrValue<BytesLike>,
      arg1: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<void>;

    parseInputs(
      _callData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<SwapDataStructOutput>;
  };

  filters: {};

  estimateGas: {
    execute(
      data: PromiseOrValue<BytesLike>,
      arg1: PromiseOrValue<BigNumberish>[],
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    parseInputs(
      _callData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    execute(
      data: PromiseOrValue<BytesLike>,
      arg1: PromiseOrValue<BigNumberish>[],
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    parseInputs(
      _callData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
