export const config = {
  mpa: {
    core: {
      ServiceRegistry: {
        name: 'ServiceRegistry',
        deploy: false,
        address: '0x73024Ec24c03904A4b5FBfa249B410891C12407b',
        serviceRegistryName: '',
        history: [],
        constructorArgs: [0],
      },
      OperationExecutor: {
        name: 'OperationExecutor',
        deploy: true,
        address: '',
        serviceRegistryName: 'OperationExecutor_2',
        history: [],
        constructorArgs: ['address:ServiceRegistry'],
      },
      OperationStorage: {
        name: 'OperationStorage',
        deploy: false,
        address: '',
        serviceRegistryName: 'OperationStorage_2',
        history: [],
        constructorArgs: ['address:ServiceRegistry', 'address:OperationExecutor'],
      },
      OperationRegistry: {
        name: 'OperationsRegistry',
        deploy: false,
        address: '',
        serviceRegistryName: 'OperationsRegistry_2',
        history: [],
        constructorArgs: [],
      },
      AccountGuard: {
        name: 'AccountGuard',
        deploy: false,
        address: '',
        serviceRegistryName: '',
        history: [],
        constructorArgs: [],
      },
      AccountFactory: {
        name: 'AccountFactory',
        deploy: false,
        address: '',
        serviceRegistryName: '',
        history: [],
        constructorArgs: ['address:AccountGuard'],
      },
    },
    actions: {
      PositionCreated: {
        name: 'PositionCreated',
        deploy: true,
        address: '',
        serviceRegistryName: 'PositionCreated',
        history: [],
        constructorArgs: [],
      },
      SwapAction: {
        name: 'SwapAction',
        deploy: true,
        address: '',
        serviceRegistryName: 'SwapAction_3',
        history: [],
        constructorArgs: ['address:ServiceRegistry'],
      },
      TakeFlashloan: {
        name: 'TakeFlashloan',
        deploy: true,
        address: '',
        serviceRegistryName: 'TakeFlashloan_3',
        history: [],
        constructorArgs: ['address:ServiceRegistry', '0x6B175474E89094C44Da98b954EedeAC495271d0F'],
      },
      SetApproval: {
        name: 'SetApproval',
        deploy: true,
        address: '',
        serviceRegistryName: 'SetApproval_3',
        history: [],
        constructorArgs: ['address:ServiceRegistry'],
      },
      PullToken: {
        name: 'PullToken',
        deploy: true,
        address: '',
        serviceRegistryName: 'PullToken_3',
        history: [],
        constructorArgs: [],
      },
      SendToken: {
        name: 'SendToken',
        deploy: true,
        address: '',
        serviceRegistryName: 'SendToken_4',
        history: [],
        constructorArgs: ['address:ServiceRegistry'],
      },
      WrapEth: {
        name: 'WrapEth',
        deploy: true,
        address: '',
        serviceRegistryName: 'WrapEth_3',
        history: [],
        constructorArgs: ['address:ServiceRegistry'],
      },
      UnwrapEth: {
        name: 'UnwrapEth',
        deploy: true,
        address: '',
        serviceRegistryName: 'UnwrapEth_3',
        history: [],
        constructorArgs: ['address:ServiceRegistry'],
      },
      ReturnFunds: {
        name: 'ReturnFunds',
        deploy: true,
        address: '',
        serviceRegistryName: 'ReturnFunds_3',
        history: [],
        constructorArgs: [],
      },
      AaveBorrow: {
        name: 'AaveBorrow',
        deploy: true,
        address: '',
        serviceRegistryName: 'AaveBorrow_3',
        history: [],
        constructorArgs: ['address:ServiceRegistry'],
      },
      AaveWithdraw: {
        name: 'AaveWithdraw',
        deploy: true,
        address: '',
        serviceRegistryName: 'AaveWithdraw_3',
        history: [],
        constructorArgs: ['address:ServiceRegistry'],
      },
      AaveDeposit: {
        name: 'AaveDeposit',
        deploy: true,
        address: '',
        serviceRegistryName: 'AaveDeposit_3',
        history: [],
        constructorArgs: ['address:ServiceRegistry'],
      },
      AavePayback: {
        name: 'AavePayback',
        deploy: true,
        address: '',
        serviceRegistryName: 'AavePayback_3',
        history: [],
        constructorArgs: ['address:ServiceRegistry'],
      },
    },
  },
  common: {
    GNOSIS_SAFE: {
      name: 'GnosisSafe',
      address: '0x41A92d82D70005B55070dB7138b21d7c28F27CC0',
    },
    WETH: {
      name: 'WETH',
      address: '0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2',
      serviceRegistryName: 'WETH',
    },
    ETH: {
      name: 'ETH',
      address: '0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2',
      serviceRegistryName: 'ETH',
    },
    STETH: {
      name: 'STETH',
      address: '0xae7ab96520de3a18e5e111b5eaab095312d7fe84',
      serviceRegistryName: 'STETH',
    },
    WSTETH: {
      name: 'WSTETH',
      address: '0x7f39c581f595b53c5cb19bd0b3f8da6c935e2ca0',
      serviceRegistryName: 'WSTETH',
    },
    USDC: {
      name: 'USDC',
      address: '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48',
      serviceRegistryName: 'USDC',
    },
    DAI: {
      name: 'DAI',
      address: '0x6B175474E89094C44Da98b954EedeAC495271d0F',
      serviceRegistryName: 'DAI',
    },
    WBTC: {
      name: 'WBTC',
      address: '0x2260fac5e5542a773aa44fbcfedf7c193bc2c599',
      serviceRegistryName: 'WBTC',
    },
    UniswapRouterV3: {
      name: 'UniswapRouterV3',
      address: '0xe592427a0aece92de3edee1f18e0157c05861564',
      serviceRegistryName: 'UniswapRouterV3',
    },
    FlashMintModule: {
      name: 'FlashMintModule',
      address: '0x60744434d6339a6B27d73d9Eda62b6F66a0a04FA',
      serviceRegistryName: 'FlashMintModule',
    },
    BalancerVault: {
      name: 'BalancerVault',
      address: '0xBA12222222228d8Ba445958a75a0704d566BF2C8',
      serviceRegistryName: 'BalancerVault',
    },
    DsProxyRegistry: {
      name: 'DsProxyRegistry',
      address: '0x4678f0a6958e4D2Bc4F1BAF7Bc52E8F3564f3fE4',
      serviceRegistryName: 'DsProxyRegistry',
    },
    OneInchAggregator: {
      name: 'OneInchAggregator',
      address: '0x1111111254fb6c44bac0bed2854e76f90643097d',
      serviceRegistryName: 'OneInchAggregator',
    },
    authorizedCaller: {
      name: 'authorizedCaller',
      address: '0x85f9b7408afE6CEb5E46223451f5d4b832B522dc',
    },
    feeRecipient: {
      name: 'feeRecipient',
      address: '0xC7b548AD9Cf38721810246C079b2d8083aba8909',
    },
  },
  aave: {
    v2: {
      PriceOracle: '0xa50ba011c48153de246e5192c8f9258a2ba79ca9',
      lendingPool: '0x7d2768dE32b0b80b7a3454c06BdAc94A69DDc7A9',
      ProtocolDataProvider: '0x057835Ad21a177dbdd3090bB1CAE03EaCF78Fc6d',
      WETHGateway: '0xcc9a0B7c43DC2a5F023Bb9b738E45B0Ef6B06E04',
    },
    v3: {
      AaveOracle: '0x54586bE62E3c3580375aE3723C145253060Ca0C2',
      Pool: '0x87870Bca3F3fD6335C3F4ce8392D69350B4fA4E2',
      AaveProtocolDataProvider: '0x7B4EB56E7CD4b454BA8ff71E4518426369a138a3',
    },
  },
}
