import { ADDRESSES, CONTRACT_NAMES } from '@oasisdex/oasis-actions/src'

import { Config } from '../common/config-item'

export const config: Config = {
  mpa: {
    core: {
      ServiceRegistry: {
        name: 'ServiceRegistry',
        deploy: true,
        address: '',
        serviceRegistryName: '',
        history: [],
        constructorArgs: [0],
      },
      OperationExecutor: {
        name: 'OperationExecutor',
        deploy: true,
        address: '',
        serviceRegistryName: 'OperationExecutor_2',
        history: [],
        constructorArgs: ['address:ServiceRegistry'],
      },
      OperationStorage: {
        name: 'OperationStorage',
        deploy: true,
        address: '',
        serviceRegistryName: 'OperationStorage_2',
        history: [],
        constructorArgs: ['address:ServiceRegistry', 'address:OperationExecutor'],
      },
      OperationRegistry: {
        name: 'OperationsRegistry',
        deploy: true,
        address: '',
        serviceRegistryName: 'OperationsRegistry_2',
        history: [],
        constructorArgs: [],
      },
      AccountGuard: {
        name: 'AccountGuard',
        deploy: true,
        address: '',
        serviceRegistryName: '',
        history: [],
        constructorArgs: [],
      },
      AccountFactory: {
        name: 'AccountFactory',
        deploy: true,
        address: '',
        serviceRegistryName: '',
        history: [],
        constructorArgs: ['address:AccountGuard'],
      },
      ChainLogView: {
        name: 'ChainLogView',
        deploy: true,
        address: '',
        serviceRegistryName: 'ChainLogView',
        history: [],
        constructorArgs: [ADDRESSES.main.maker.chainlog],
      },
    },
    actions: {
      PositionCreated: {
        name: 'PositionCreated',
        deploy: true,
        address: '',
        serviceRegistryName: 'PositionCreated',
        history: [],
        constructorArgs: [],
      },
      SwapAction: {
        name: 'SwapAction',
        deploy: true,
        address: '',
        serviceRegistryName: 'SwapAction_3',
        history: [],
        constructorArgs: ['address:ServiceRegistry'],
      },
      TakeFlashloan: {
        name: 'TakeFlashloan',
        deploy: true,
        address: '',
        serviceRegistryName: 'TakeFlashloan_3',
        history: [],
        constructorArgs: [
          'address:ServiceRegistry',
          '0x6B175474E89094C44Da98b954EedeAC495271d0F',
          '0x5a15566417e6C1c9546523066500bDDBc53F88C7',
        ],
      },
      SetApproval: {
        name: 'SetApproval',
        deploy: true,
        address: '',
        serviceRegistryName: 'SetApproval_3',
        history: [],
        constructorArgs: ['address:ServiceRegistry'],
      },
      PullToken: {
        name: 'PullToken',
        deploy: true,
        address: '',
        serviceRegistryName: 'PullToken_3',
        history: [],
        constructorArgs: [],
      },
      SendToken: {
        name: 'SendToken',
        deploy: true,
        address: '',
        serviceRegistryName: 'SendToken_4',
        history: [],
        constructorArgs: ['address:ServiceRegistry'],
      },
      WrapEth: {
        name: 'WrapEth',
        deploy: true,
        address: '',
        serviceRegistryName: 'WrapEth_3',
        history: [],
        constructorArgs: ['address:ServiceRegistry'],
      },
      UnwrapEth: {
        name: 'UnwrapEth',
        deploy: true,
        address: '',
        serviceRegistryName: 'UnwrapEth_3',
        history: [],
        constructorArgs: ['address:ServiceRegistry'],
      },
      ReturnFunds: {
        name: 'ReturnFunds',
        deploy: true,
        address: '',
        serviceRegistryName: 'ReturnFunds_3',
        history: [],
        constructorArgs: [],
      },
      AaveBorrow: {
        name: 'AaveBorrow',
        deploy: true,
        address: '',
        serviceRegistryName: 'AaveBorrow_3',
        history: [],
        constructorArgs: ['address:ServiceRegistry'],
      },
      AaveWithdraw: {
        name: 'AaveWithdraw',
        deploy: true,
        address: '',
        serviceRegistryName: 'AaveWithdraw_3',
        history: [],
        constructorArgs: ['address:ServiceRegistry'],
      },
      AaveDeposit: {
        name: 'AaveDeposit',
        deploy: true,
        address: '',
        serviceRegistryName: 'AaveDeposit_3',
        history: [],
        constructorArgs: ['address:ServiceRegistry'],
      },
      AavePayback: {
        name: 'AavePayback',
        deploy: true,
        address: '',
        serviceRegistryName: 'AavePayback_3',
        history: [],
        constructorArgs: ['address:ServiceRegistry'],
      },
      AaveV3Borrow: {
        name: 'AaveV3Borrow',
        deploy: true,
        address: '',
        serviceRegistryName: 'AaveV3Borrow',
        history: [],
        constructorArgs: ['address:ServiceRegistry'],
      },
      AaveV3Withdraw: {
        name: 'AaveV3Withdraw',
        deploy: true,
        address: '',
        serviceRegistryName: 'AaveV3Withdraw',
        history: [],
        constructorArgs: ['address:ServiceRegistry'],
      },
      AaveV3Deposit: {
        name: 'AaveV3Deposit',
        deploy: true,
        address: '',
        serviceRegistryName: 'AaveV3Deposit',
        history: [],
        constructorArgs: ['address:ServiceRegistry'],
      },
      AaveV3Payback: {
        name: 'AaveV3Payback',
        deploy: true,
        address: '',
        serviceRegistryName: 'AaveV3Payback',
        history: [],
        constructorArgs: ['address:ServiceRegistry'],
      },
      AaveV3SetEMode: {
        name: 'AaveV3SetEMode',
        deploy: true,
        address: '',
        serviceRegistryName: 'AaveV3SetEMode',
        history: [],
        constructorArgs: ['address:ServiceRegistry'],
      },
    },
  },
  common: {
    WETH: {
      name: 'WETH',
      address: ADDRESSES.main.WETH,
      serviceRegistryName: CONTRACT_NAMES.common.WETH,
    },
    ETH: {
      name: 'ETH',
      address: ADDRESSES.main.ETH,
    },
    STETH: {
      name: 'STETH',
      address: ADDRESSES.main.STETH,
      serviceRegistryName: CONTRACT_NAMES.common.STETH,
    },
    WSTETH: {
      name: 'WSTETH',
      address: ADDRESSES.main.WSTETH,
      serviceRegistryName: CONTRACT_NAMES.common.WSTETH,
    },
    USDC: {
      name: 'USDC',
      address: ADDRESSES.main.USDC,
      serviceRegistryName: CONTRACT_NAMES.common.USDC,
    },
    DAI: {
      name: 'DAI',
      address: ADDRESSES.main.DAI,
      serviceRegistryName: CONTRACT_NAMES.common.DAI,
    },
    WBTC: {
      name: 'WBTC',
      address: ADDRESSES.main.WBTC,
      serviceRegistryName: CONTRACT_NAMES.common.WBTC,
    },
    UniswapRouterV3: {
      name: 'UniswapRouterV3',
      address: ADDRESSES.main.uniswapRouterV3,
      serviceRegistryName: CONTRACT_NAMES.common.UNISWAP_ROUTER,
    },
    FlashMintModule: {
      name: 'FlashMintModule',
      address: ADDRESSES.main.maker.fmm,
      serviceRegistryName: CONTRACT_NAMES.maker.FLASH_MINT_MODULE,
    },
    BalancerVault: {
      name: 'BalancerVault',
      address: '0xBA12222222228d8Ba445958a75a0704d566BF2C8',
      serviceRegistryName: CONTRACT_NAMES.common.BALANCER_VAULT,
    },
    DsProxyRegistry: {
      name: 'DsProxyRegistry',
      address: ADDRESSES.main.proxyRegistry,
    },
    OneInchAggregator: {
      name: 'OneInchAggregator',
      address: '0x1111111254fb6c44bac0bed2854e76f90643097d',
      serviceRegistryName: CONTRACT_NAMES.common.ONE_INCH_AGGREGATOR,
    },
    AuthorizedCaller: {
      name: 'AuthorizedCaller',
      address: '0x85f9b7408afE6CEb5E46223451f5d4b832B522dc',
    },
    FeeRecipient: {
      name: 'FeeRecipient',
      address: '0xC7b548AD9Cf38721810246C079b2d8083aba8909',
    },
    ChainlinkEthUsdPriceFeed: {
      name: 'ChainlinkEthUsdPriceFeed',
      address: '0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419',
    },
  },
  aave: {
    v2: {
      PriceOracle: {
        name: 'PriceOracle',
        address: '0xa50ba011c48153de246e5192c8f9258a2ba79ca9',
      },
      LendingPool: {
        name: 'LendingPool',
        address: '0x7d2768dE32b0b80b7a3454c06BdAc94A69DDc7A9',
        serviceRegistryName: CONTRACT_NAMES.aave.v2.LENDING_POOL,
      },
      ProtocolDataProvider: {
        name: 'ProtocolDataProvider',
        address: '0x057835Ad21a177dbdd3090bB1CAE03EaCF78Fc6d',
      },
      WETHGateway: {
        name: 'WETHGateway',
        address: '0xcc9a0B7c43DC2a5F023Bb9b738E45B0Ef6B06E04',
        serviceRegistryName: CONTRACT_NAMES.aave.v2.WETH_GATEWAY,
      },
    },
    v3: {
      AaveOracle: {
        name: 'AaveOracle',
        address: '0x54586bE62E3c3580375aE3723C145253060Ca0C2',
      },
      Pool: {
        name: 'Pool',
        address: '0x87870Bca3F3fD6335C3F4ce8392D69350B4fA4E2',
        serviceRegistryName: CONTRACT_NAMES.aave.v3.AAVE_POOL,
      },
      AaveProtocolDataProvider: {
        name: 'AaveProtocolDataProvider',
        address: '0x7B4EB56E7CD4b454BA8ff71E4518426369a138a3',
      },
    },
  },
}
