/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as aave from "./aave";
export type { aave };
import type * as ajna from "./ajna";
export type { ajna };
import type * as common from "./common";
export type { common };
import type * as maker from "./maker";
export type { maker };
import type * as morphoBlue from "./morpho-blue";
export type { morphoBlue };
import type * as spark from "./spark";
export type { spark };
