/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  SparkSetEMode,
  SparkSetEModeInterface,
} from "../../../../../../system/contracts/actions/spark/SetEMode.sol/SparkSetEMode";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_registry",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
      {
        internalType: "uint8[]",
        name: "",
        type: "uint8[]",
      },
    ],
    name: "execute",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "_callData",
        type: "bytes",
      },
    ],
    name: "parseInputs",
    outputs: [
      {
        components: [
          {
            internalType: "uint8",
            name: "categoryId",
            type: "uint8",
          },
        ],
        internalType: "struct SetEModeData",
        name: "params",
        type: "tuple",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
] as const;

export class SparkSetEMode__factory {
  static readonly abi = _abi;
  static createInterface(): SparkSetEModeInterface {
    return new utils.Interface(_abi) as SparkSetEModeInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): SparkSetEMode {
    return new Contract(address, _abi, signerOrProvider) as SparkSetEMode;
  }
}
