/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IajnaProxyActions,
  IajnaProxyActionsInterface,
} from "../../../../../../system/contracts/ajna/ajna-actions/AjnaRewardClaimer.sol/IajnaProxyActions";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "pool",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "claimRewardsAndSendToOwner",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IajnaProxyActions__factory {
  static readonly abi = _abi;
  static createInterface(): IajnaProxyActionsInterface {
    return new utils.Interface(_abi) as IajnaProxyActionsInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IajnaProxyActions {
    return new Contract(address, _abi, signerOrProvider) as IajnaProxyActions;
  }
}
