/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IMorphoFlashLoanCallback__factory } from "./IMorphoFlashLoanCallback__factory";
export { IMorphoLiquidateCallback__factory } from "./IMorphoLiquidateCallback__factory";
export { IMorphoRepayCallback__factory } from "./IMorphoRepayCallback__factory";
export { IMorphoSupplyCallback__factory } from "./IMorphoSupplyCallback__factory";
export { IMorphoSupplyCollateralCallback__factory } from "./IMorphoSupplyCollateralCallback__factory";
