/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  Executable,
  ExecutableInterface,
} from "../../../../../system/contracts/actions/common/Executable";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
      {
        internalType: "uint8[]",
        name: "paramsMap",
        type: "uint8[]",
      },
    ],
    name: "execute",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
] as const;

export class Executable__factory {
  static readonly abi = _abi;
  static createInterface(): ExecutableInterface {
    return new Interface(_abi) as ExecutableInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): Executable {
    return new Contract(address, _abi, runner) as unknown as Executable;
  }
}
