/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  UnwrapEth,
  UnwrapEthInterface,
} from "../../../../../system/contracts/actions/common/UnwrapEth";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_registry",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
      {
        internalType: "uint8[]",
        name: "paramsMap",
        type: "uint8[]",
      },
    ],
    name: "execute",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "_callData",
        type: "bytes",
      },
    ],
    name: "parseInputs",
    outputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "amount",
            type: "uint256",
          },
        ],
        internalType: "struct UnwrapEthData",
        name: "params",
        type: "tuple",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
] as const;

export class UnwrapEth__factory {
  static readonly abi = _abi;
  static createInterface(): UnwrapEthInterface {
    return new utils.Interface(_abi) as UnwrapEthInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): UnwrapEth {
    return new Contract(address, _abi, signerOrProvider) as UnwrapEth;
  }
}
