/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  Signer,
  utils,
} from "ethers";
import type { EventFragment } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../../../../common";

export interface IERC721PoolEventsInterface extends utils.Interface {
  functions: {};

  events: {
    "AddCollateralNFT(address,uint256,uint256[],uint256)": EventFragment;
    "DrawDebtNFT(address,uint256,uint256[],uint256)": EventFragment;
    "MergeOrRemoveCollateralNFT(address,uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AddCollateralNFT"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "DrawDebtNFT"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "MergeOrRemoveCollateralNFT"): EventFragment;
}

export interface AddCollateralNFTEventObject {
  actor: string;
  index: BigNumber;
  tokenIds: BigNumber[];
  lpAwarded: BigNumber;
}
export type AddCollateralNFTEvent = TypedEvent<
  [string, BigNumber, BigNumber[], BigNumber],
  AddCollateralNFTEventObject
>;

export type AddCollateralNFTEventFilter =
  TypedEventFilter<AddCollateralNFTEvent>;

export interface DrawDebtNFTEventObject {
  borrower: string;
  amountBorrowed: BigNumber;
  tokenIdsPledged: BigNumber[];
  lup: BigNumber;
}
export type DrawDebtNFTEvent = TypedEvent<
  [string, BigNumber, BigNumber[], BigNumber],
  DrawDebtNFTEventObject
>;

export type DrawDebtNFTEventFilter = TypedEventFilter<DrawDebtNFTEvent>;

export interface MergeOrRemoveCollateralNFTEventObject {
  actor: string;
  collateralMerged: BigNumber;
  toIndexLps: BigNumber;
}
export type MergeOrRemoveCollateralNFTEvent = TypedEvent<
  [string, BigNumber, BigNumber],
  MergeOrRemoveCollateralNFTEventObject
>;

export type MergeOrRemoveCollateralNFTEventFilter =
  TypedEventFilter<MergeOrRemoveCollateralNFTEvent>;

export interface IERC721PoolEvents extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IERC721PoolEventsInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {};

  callStatic: {};

  filters: {
    "AddCollateralNFT(address,uint256,uint256[],uint256)"(
      actor?: PromiseOrValue<string> | null,
      index?: PromiseOrValue<BigNumberish> | null,
      tokenIds?: null,
      lpAwarded?: null
    ): AddCollateralNFTEventFilter;
    AddCollateralNFT(
      actor?: PromiseOrValue<string> | null,
      index?: PromiseOrValue<BigNumberish> | null,
      tokenIds?: null,
      lpAwarded?: null
    ): AddCollateralNFTEventFilter;

    "DrawDebtNFT(address,uint256,uint256[],uint256)"(
      borrower?: PromiseOrValue<string> | null,
      amountBorrowed?: null,
      tokenIdsPledged?: null,
      lup?: null
    ): DrawDebtNFTEventFilter;
    DrawDebtNFT(
      borrower?: PromiseOrValue<string> | null,
      amountBorrowed?: null,
      tokenIdsPledged?: null,
      lup?: null
    ): DrawDebtNFTEventFilter;

    "MergeOrRemoveCollateralNFT(address,uint256,uint256)"(
      actor?: PromiseOrValue<string> | null,
      collateralMerged?: null,
      toIndexLps?: null
    ): MergeOrRemoveCollateralNFTEventFilter;
    MergeOrRemoveCollateralNFT(
      actor?: PromiseOrValue<string> | null,
      collateralMerged?: null,
      toIndexLps?: null
    ): MergeOrRemoveCollateralNFTEventFilter;
  };

  estimateGas: {};

  populateTransaction: {};
}
