/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../common";

export interface DummyAutomationInterface extends utils.Interface {
  functions: {
    "doAutomationStuffDelegateCall(bytes,address,uint256,address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "doAutomationStuffDelegateCall"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "doAutomationStuffDelegateCall",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "doAutomationStuffDelegateCall",
    data: BytesLike
  ): Result;

  events: {};
}

export interface DummyAutomation extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: DummyAutomationInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    doAutomationStuffDelegateCall(
      executionData: PromiseOrValue<BytesLike>,
      opExecutorAddress: PromiseOrValue<string>,
      vaultId: PromiseOrValue<BigNumberish>,
      commandAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  doAutomationStuffDelegateCall(
    executionData: PromiseOrValue<BytesLike>,
    opExecutorAddress: PromiseOrValue<string>,
    vaultId: PromiseOrValue<BigNumberish>,
    commandAddress: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    doAutomationStuffDelegateCall(
      executionData: PromiseOrValue<BytesLike>,
      opExecutorAddress: PromiseOrValue<string>,
      vaultId: PromiseOrValue<BigNumberish>,
      commandAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    doAutomationStuffDelegateCall(
      executionData: PromiseOrValue<BytesLike>,
      opExecutorAddress: PromiseOrValue<string>,
      vaultId: PromiseOrValue<BigNumberish>,
      commandAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    doAutomationStuffDelegateCall(
      executionData: PromiseOrValue<BytesLike>,
      opExecutorAddress: PromiseOrValue<string>,
      vaultId: PromiseOrValue<BigNumberish>,
      commandAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
