import { ADDRESS_ZERO, loadContractNames } from '@deploy-configurations/constants'
import { SystemConfig } from '@deploy-configurations/types/deployment-config'
import { Network } from '@deploy-configurations/types/network'

const SERVICE_REGISTRY_NAMES = loadContractNames(Network.ARBITRUM)

export const config: SystemConfig = {
  mpa: {
    core: {
      ServiceRegistry: {
        name: 'ServiceRegistry',
        deploy: false,
        address: '0xf22f17b1d2354b4f4f52e4d164e4eb5e1f0a6ba6',
        history: [],
        constructorArgs: [0],
      },
      OperationExecutor: {
        name: 'OperationExecutor',
        deploy: false,
        address: '0x90feaf7727a6ce75f518728d296877830fd39a49',
        serviceRegistryName: SERVICE_REGISTRY_NAMES.common.OPERATION_EXECUTOR,
        history: [],
        constructorArgs: ['address:ServiceRegistry'],
      },
      OperationStorage: {
        name: 'OperationStorage',
        deploy: false,
        address: '0xd4FEaf1023CD6998053a1eb02460000980Cc908f',
        serviceRegistryName: SERVICE_REGISTRY_NAMES.common.OPERATION_STORAGE,
        history: [],
        constructorArgs: ['address:ServiceRegistry', 'address:OperationExecutor'],
      },
      OperationsRegistry: {
        name: 'OperationsRegistry',
        deploy: false,
        address: '0x392ACeBea829373A3eFDc0dA80a16003106d8f6E',
        serviceRegistryName: SERVICE_REGISTRY_NAMES.common.OPERATIONS_REGISTRY,
        history: [],
        constructorArgs: [],
      },
      DSProxyFactory: {
        name: 'DSProxyFactory',
        deploy: false,
        address: '0x63059cC2533344B65372983D4B6258b2cbbBF0Da',
        serviceRegistryName: SERVICE_REGISTRY_NAMES.common.DS_PROXY_FACTORY,
        history: [],
        constructorArgs: [],
      },
      DSProxyRegistry: {
        name: 'DSProxyRegistry',
        deploy: false,
        address: '0x9319710C25cdaDDD1766F0bDE40F1A4034C17c7e',
        serviceRegistryName: SERVICE_REGISTRY_NAMES.common.DS_PROXY_REGISTRY,
        history: [],
        constructorArgs: ['address:DSProxyFactory'],
      },
      DSGuardFactory: {
        name: 'DSGuardFactory',
        deploy: false,
        address: '0x98C7C60924170B709D1a8aA6Fbb443190E3296CD',
        serviceRegistryName: SERVICE_REGISTRY_NAMES.common.DS_GUARD_FACTORY,
        history: [],
        constructorArgs: [],
      },
      AccountGuard: {
        name: 'AccountGuard',
        deploy: false,
        address: '0x746a6f9Acb42bcB43C08C829A035DBa7Db9E7385',
        serviceRegistryName: SERVICE_REGISTRY_NAMES.common.ACCOUNT_GUARD,
        history: [],
        constructorArgs: [],
      },
      AccountFactory: {
        name: 'AccountFactory',
        deploy: false,
        address: '0xCcB155E5B2A3201d5e10EdAa6e9F908871d1722B',
        serviceRegistryName: SERVICE_REGISTRY_NAMES.common.ACCOUNT_FACTORY,
        history: [],
        constructorArgs: ['address:AccountGuard'],
      },
      Swap: {
        name: 'Swap',
        deploy: false,
        address: '0x6166B1587be6B954e660A71e4B083A5e0a5bF1b6',
        serviceRegistryName: SERVICE_REGISTRY_NAMES.common.SWAP,
        history: [],
        constructorArgs: [
          '0x0B5a3C04D1199283938fbe887A2C82C808aa89Fb',
          '0x67e30ba093148e835f47Fd5dcf1AF7D0c58E0f6b',
          20,
          'address:ServiceRegistry',
        ],
      },
    },
    actions: {
      PositionCreated: {
        name: 'PositionCreated',
        deploy: false,
        address: '0xeB54C366512c4d59A222A251ea7316568859E08C',
        serviceRegistryName: SERVICE_REGISTRY_NAMES.common.POSITION_CREATED,
        history: [],
        constructorArgs: [],
      },
      SwapAction: {
        name: 'SwapAction',
        deploy: false,
        address: '0x43C9a445fCf3bc3d1483c0b90DC0346249c0D84C',
        serviceRegistryName: SERVICE_REGISTRY_NAMES.common.SWAP_ACTION,
        history: [],
        constructorArgs: ['address:ServiceRegistry'],
      },
      TakeFlashloan: {
        name: 'TakeFlashloan',
        deploy: false,
        address: '0x7E7EB65A93441a2D2Bf0941216b4c1116B554d85',
        serviceRegistryName: SERVICE_REGISTRY_NAMES.common.TAKE_A_FLASHLOAN,
        history: [],
        constructorArgs: ['address:ServiceRegistry', ADDRESS_ZERO, 'address:DSGuardFactory'],
      },
      SetApproval: {
        name: 'SetApproval',
        deploy: false,
        address: '0xAC0B1652388Ea425884e6b60e2eD30155f43D50b',
        serviceRegistryName: SERVICE_REGISTRY_NAMES.common.SET_APPROVAL,
        history: [],
        constructorArgs: ['address:ServiceRegistry'],
      },
      PullToken: {
        name: 'PullToken',
        deploy: false,
        address: '0x645325494A37d35cf6baFc82C3e6bcE4473F2685',
        serviceRegistryName: SERVICE_REGISTRY_NAMES.common.PULL_TOKEN,
        history: [],
        constructorArgs: [],
      },
      SendToken: {
        name: 'SendToken',
        deploy: false,
        address: '0xb3f0C5E4012aF22359c9Ab233DABd80cD81F5ec5',
        serviceRegistryName: SERVICE_REGISTRY_NAMES.common.SEND_TOKEN,
        history: [],
        constructorArgs: ['address:ServiceRegistry'],
      },
      WrapEth: {
        name: 'WrapEth',
        deploy: false,
        address: '0x2006d4e76A398c78964F7e311BFd7Ccb149EaFE2',
        serviceRegistryName: SERVICE_REGISTRY_NAMES.common.WRAP_ETH,
        history: [],
        constructorArgs: ['address:ServiceRegistry'],
      },
      UnwrapEth: {
        name: 'UnwrapEth',
        deploy: false,
        address: '0xA0Cb87300aB07D00468704cD8f016F8dE47D8E0A',
        serviceRegistryName: SERVICE_REGISTRY_NAMES.common.UNWRAP_ETH,
        history: [],
        constructorArgs: ['address:ServiceRegistry'],
      },
      ReturnFunds: {
        name: 'ReturnFunds',
        deploy: false,
        address: '0x063E4242CD7C2421f67e21D7297c74bbDFEF7b0E',
        serviceRegistryName: SERVICE_REGISTRY_NAMES.common.RETURN_FUNDS,
        history: [],
        constructorArgs: [],
      },
      AaveV3Borrow: {
        name: 'AaveV3Borrow',
        deploy: false,
        address: '0xe1D974cAB854a65b2005A1cbF9D627D90DAb70c2',
        serviceRegistryName: SERVICE_REGISTRY_NAMES.aave.v3.BORROW,
        history: [],
        constructorArgs: ['address:ServiceRegistry'],
      },
      AaveV3Withdraw: {
        name: 'AaveV3Withdraw',
        deploy: false,
        address: '0xCe91349d2A4577BBd0fC91Fe6019600e047f2847',
        serviceRegistryName: SERVICE_REGISTRY_NAMES.aave.v3.WITHDRAW,
        history: [],
        constructorArgs: ['address:ServiceRegistry'],
      },
      AaveV3Deposit: {
        name: 'AaveV3Deposit',
        deploy: false,
        address: '0xbCC3813520bCCd64d55CEA370948198EDFB03ee3',
        serviceRegistryName: SERVICE_REGISTRY_NAMES.aave.v3.DEPOSIT,
        history: [],
        constructorArgs: ['address:ServiceRegistry'],
      },
      AaveV3Payback: {
        name: 'AaveV3Payback',
        deploy: false,
        address: '0xF7B75183A2829843dB06266c114297dfbFaeE2b6',
        serviceRegistryName: SERVICE_REGISTRY_NAMES.aave.v3.PAYBACK,
        history: [],
        constructorArgs: ['address:ServiceRegistry'],
      },
      AaveV3SetEMode: {
        name: 'AaveV3SetEMode',
        deploy: false,
        address: '0x71B16bF494a868a632189324e219470d2cD46863',
        serviceRegistryName: SERVICE_REGISTRY_NAMES.aave.v3.SET_EMODE,
        history: [],
        constructorArgs: ['address:ServiceRegistry'],
      },
      AjnaDepositBorrow: {
        name: 'AjnaDepositBorrow',
        deploy: true,
        address: '',
        serviceRegistryName: SERVICE_REGISTRY_NAMES.ajna.DEPOSIT_BORROW,
        history: [],
        constructorArgs: ['address:ServiceRegistry'],
      },
      AjnaRepayWithdraw: {
        name: 'AjnaRepayWithdraw',
        deploy: true,
        address: '',
        serviceRegistryName: SERVICE_REGISTRY_NAMES.ajna.REPAY_WITHDRAW,
        history: [],
        constructorArgs: ['address:ServiceRegistry'],
      },
    },
  },
  common: {
    GnosisSafe: { name: 'GnosisSafe', address: '' },
    UniswapRouterV3: {
      name: 'UniswapRouterV3',
      address: '0xe592427a0aece92de3edee1f18e0157c05861564',
      serviceRegistryName: SERVICE_REGISTRY_NAMES.common.UNISWAP_ROUTER,
    },
    BalancerVault: {
      name: 'BalancerVault',
      address: '0xBA12222222228d8Ba445958a75a0704d566BF2C8',
      serviceRegistryName: SERVICE_REGISTRY_NAMES.common.BALANCER_VAULT,
    },
    FeeRecipient: { name: 'FeeRecipient', address: '' },
    AuthorizedCaller: { name: 'AuthorizedCaller', address: '' },
    OneInchAggregator: {
      name: 'OneInchAggregator',
      address: '0x1111111254EEB25477B68fb85Ed929f73A960582',
      serviceRegistryName: SERVICE_REGISTRY_NAMES.common.ONE_INCH_AGGREGATOR,
    },
    MerkleRedeemer: { name: 'MerkleRedeemer', address: '' },
    DssCharter: { name: 'DssCharter', address: '' },
    DssProxyActions: { name: 'DssProxyActions', address: '' },
    DssProxyActionsCharter: { name: 'DssProxyActionsCharter', address: '' },
    DssMultiplyProxyActions: { name: 'DssMultiplyProxyActions', address: '' },
    DssCropper: { name: 'DssCropper', address: '' },
    DssProxyActionsCropjoin: { name: 'DssProxyActionsCropjoin', address: '' },
    DssProxyActionsDsr: { name: 'DssProxyActionsDsr', address: '' },
    Otc: { name: 'Otc', address: '' },
    OtcSupportMethods: { name: 'OtcSupportMethods', address: '' },
    ServiceRegistry: { name: 'ServiceRegistry', address: '' },
    GuniProxyActions: { name: 'GuniProxyActions', address: '' },
    GuniResolver: { name: 'GuniResolver', address: '' },
    GuniRouter: { name: 'GuniRouter', address: '' },
    CdpRegistry: { name: 'CdpRegistry', address: '' },
    DefaultExchange: { name: 'DefaultExchange', address: '' },
    NoFeesExchange: { name: 'NoFeesExchange', address: '' },
    LowerFeesExchange: { name: 'LowerFeesExchange', address: '' },
    LidoCrvLiquidityFarmingReward: { name: 'LidoCrvLiquidityFarmingReward', address: '' },
    ChainlinkPriceOracle_USDCUSD: {
      name: 'ChainlinkPriceOracle_USDCUSD',
      address: '0x50834f3163758fcc1df9973b6e91f0f0f0434ad3',
    },
    ChainlinkPriceOracle_ETHUSD: {
      name: 'ChainlinkPriceOracle_ETHUSD',
      address: '0x639fe6ab55c921f74e7fac1ee960c0b6293ba612',
    },
    SdaiOracle: {
      name: 'SdaiOracle',
      address: ADDRESS_ZERO,
    },
    ADAI: {
      name: 'ADAI',
      address: ADDRESS_ZERO,
    },
    AAVE: {
      name: 'AAVE',
      address: ADDRESS_ZERO,
    },
    BAL: {
      name: 'BAL',
      address: ADDRESS_ZERO,
    },
    BAT: {
      name: 'BAT',
      address: ADDRESS_ZERO,
    },
    CBETH: {
      name: 'CBETH',
      address: ADDRESS_ZERO,
    },
    COMP: {
      name: 'COMP',
      address: ADDRESS_ZERO,
    },
    CRVV1ETHSTETH: {
      name: 'CRVV1ETHSTETH',
      address: ADDRESS_ZERO,
    },
    DAI: {
      name: 'DAI',
      address: '0xda10009cbd5d07dd0cecc66161fc93d7c9000da1',
      serviceRegistryName: SERVICE_REGISTRY_NAMES.common.DAI,
    },
    ETH: {
      name: 'ETH',
      address: '0x82aF49447D8a07e3bd95BD0d56f35241523fBab1',
    },
    FRAX: { name: 'FRAX', address: ADDRESS_ZERO },
    LUSD: { name: 'LUSD', address: ADDRESS_ZERO },
    GHO: { name: 'GHO', address: ADDRESS_ZERO },
    GNO: {
      name: 'GNO',
      address: ADDRESS_ZERO,
    },
    GUNIV3DAIUSDC1: { name: 'GUNIV3DAIUSDC1', address: '' },
    GUNIV3DAIUSDC2: { name: 'GUNIV3DAIUSDC2', address: '' },
    GUSD: {
      name: 'GUSD',
      address: ADDRESS_ZERO,
    },
    KNC: {
      name: 'KNC',
      address: ADDRESS_ZERO,
    },
    LDO: {
      name: 'LDO',
      address: ADDRESS_ZERO,
    },
    LINK: {
      name: 'LINK',
      address: ADDRESS_ZERO,
    },
    LRC: {
      name: 'LRC',
      address: ADDRESS_ZERO,
    },
    MANA: {
      name: 'MANA',
      address: ADDRESS_ZERO,
    },
    MATIC: {
      name: 'MATIC',
      address: ADDRESS_ZERO,
    },
    PAX: {
      name: 'PAX',
      address: ADDRESS_ZERO,
    },
    PAXUSD: {
      name: 'PAXUSD',
      address: ADDRESS_ZERO,
    },
    RENBTC: {
      name: 'RENBTC',
      address: ADDRESS_ZERO,
    },
    RETH: {
      name: 'RETH',
      address: ADDRESS_ZERO,
    },
    RWA001: {
      name: 'RWA001',
      address: ADDRESS_ZERO,
    },
    RWA002: {
      name: 'RWA002',
      address: ADDRESS_ZERO,
    },
    RWA003: {
      name: 'RWA003',
      address: ADDRESS_ZERO,
    },
    RWA004: {
      name: 'RWA004',
      address: ADDRESS_ZERO,
    },
    RWA005: {
      name: 'RWA005',
      address: ADDRESS_ZERO,
    },
    RWA006: {
      name: 'RWA006',
      address: ADDRESS_ZERO,
    },
    SDAI: { name: 'SDAI', address: ADDRESS_ZERO },
    STETH: {
      name: 'STETH',
      address: ADDRESS_ZERO,
    },
    TUSD: {
      name: 'TUSD',
      address: ADDRESS_ZERO,
    },
    TBTC: { name: 'TBTC', address: ADDRESS_ZERO },
    UNI: {
      name: 'UNI',
      address: ADDRESS_ZERO,
    },
    UNIV2AAVEETH: {
      name: 'UNIV2AAVEETH',
      address: ADDRESS_ZERO,
    },
    UNIV2DAIETH: {
      name: 'UNIV2DAIETH',
      address: ADDRESS_ZERO,
    },
    UNIV2DAIUSDC: {
      name: 'UNIV2DAIUSDC',
      address: ADDRESS_ZERO,
    },
    UNIV2DAIUSDT: {
      name: 'UNIV2DAIUSDT',
      address: ADDRESS_ZERO,
    },
    UNIV2ETHUSDT: {
      name: 'UNIV2ETHUSDT',
      address: ADDRESS_ZERO,
    },
    UNIV2LINKETH: {
      name: 'UNIV2LINKETH',
      address: ADDRESS_ZERO,
    },
    UNIV2UNIETH: {
      name: 'UNIV2UNIETH',
      address: ADDRESS_ZERO,
    },
    UNIV2USDCETH: {
      name: 'UNIV2USDCETH',
      address: ADDRESS_ZERO,
    },
    UNIV2WBTCDAI: {
      name: 'UNIV2WBTCDAI',
      address: ADDRESS_ZERO,
    },
    UNIV2WBTCETH: {
      name: 'UNIV2WBTCETH',
      address: ADDRESS_ZERO,
    },
    USDC: {
      name: 'USDC',
      address: '0xff970a61a04b1ca14834a43f5de4533ebddb5cc8',
      serviceRegistryName: SERVICE_REGISTRY_NAMES.common.USDC,
    },
    USDBC: {
      name: 'USDBC',
      address: ADDRESS_ZERO,
    },
    USDT: {
      name: 'USDT',
      address: ADDRESS_ZERO,
    },
    WBTC: {
      name: 'WBTC',
      address: '0x2f2a2543b76a4166549f7aab2e75bef0aefc5b0f',
      serviceRegistryName: SERVICE_REGISTRY_NAMES.common.WBTC,
    },
    WETH: {
      name: 'WETH',
      address: '0x82aF49447D8a07e3bd95BD0d56f35241523fBab1',
      serviceRegistryName: SERVICE_REGISTRY_NAMES.common.WETH,
    },
    WLD: { name: 'WLD', address: ADDRESS_ZERO },
    WSTETH: {
      name: 'WSTETH',
      address: '0x5979D7b546E38E414F7E9822514be443A4800529',
      serviceRegistryName: SERVICE_REGISTRY_NAMES.common.WSTETH,
    },
    YIELDBTC: {
      name: 'YIELDBTC',
      address: ADDRESS_ZERO,
    },
    YIELDETH: {
      name: 'YIELDETH',
      address: ADDRESS_ZERO,
    },
    YFI: {
      name: 'YFI',
      address: ADDRESS_ZERO,
    },
    ZRX: {
      name: 'ZRX',
      address: ADDRESS_ZERO,
    },
  },
  aave: {
    v2: {
      Oracle: { name: 'Oracle', address: '' },
      LendingPool: { name: 'LendingPool', address: '' },
      PoolDataProvider: { name: 'PoolDataProvider', address: '' },
      WETHGateway: { name: 'WETHGateway', address: '' },
    },
    v3: {
      Oracle: {
        name: 'Oracle',
        address: '0xb56c2F0B653B2e0b10C9b928C8580Ac5Df02C7C7',
      },
      LendingPool: {
        name: 'LendingPool',
        address: '0x794a61358D6845594F94dc1DB02A252b5b4814aD',
        serviceRegistryName: SERVICE_REGISTRY_NAMES.aave.v3.AAVE_POOL,
      },
      PoolDataProvider: {
        name: 'PoolDataProvider',
        address: '0x69FA688f1Dc47d4B5d8029D5a35FB7a548310654',
      },
      L2Encoder: {
        name: 'L2Encoder',
        address: '0x9abADECD08572e0eA5aF4d47A9C7984a5AA503dC',
      },
    },
  },
  spark: {},
  maker: {
    common: {
      FlashMintModule: { name: 'FlashMintModule', address: '' },
      Chainlog: { name: 'Chainlog', address: '' },
      CdpManager: { name: 'CdpManager', address: '' },
      GetCdps: { name: 'GetCdps', address: '' },
      Jug: { name: 'Jug', address: '' },
      Pot: { name: 'Pot', address: '' },
      End: { name: 'End', address: '' },
      Spot: { name: 'Spot', address: '' },
      Dog: { name: 'Dog', address: '' },
      Vat: { name: 'Vat', address: '' },
      McdGov: { name: 'McdGov', address: '' },
    },
    joins: {
      MCD_JOIN_DAI: { name: 'MCD_JOIN_DAI', address: '' },
      MCD_JOIN_ETH_A: { name: 'MCD_JOIN_ETH_A', address: '' },
      MCD_JOIN_ETH_B: { name: 'MCD_JOIN_ETH_B', address: '' },
      MCD_JOIN_ETH_C: { name: 'MCD_JOIN_ETH_C', address: '' },
      MCD_JOIN_BAT_A: { name: 'MCD_JOIN_BAT_A', address: '' },
      MCD_JOIN_USDC_A: { name: 'MCD_JOIN_USDC_A', address: '' },
      MCD_JOIN_USDC_B: { name: 'MCD_JOIN_USDC_B', address: '' },
      MCD_JOIN_PSM_USDC_A: { name: 'MCD_JOIN_PSM_USDC_A', address: '' },
      MCD_JOIN_TUSD_A: { name: 'MCD_JOIN_TUSD_A', address: '' },
      MCD_JOIN_WBTC_A: { name: 'MCD_JOIN_WBTC_A', address: '' },
      MCD_JOIN_WBTC_B: { name: 'MCD_JOIN_WBTC_B', address: '' },
      MCD_JOIN_WBTC_C: { name: 'MCD_JOIN_WBTC_C', address: '' },
      MCD_JOIN_ZRX_A: { name: 'MCD_JOIN_ZRX_A', address: '' },
      MCD_JOIN_KNC_A: { name: 'MCD_JOIN_KNC_A', address: '' },
      MCD_JOIN_MANA_A: { name: 'MCD_JOIN_MANA_A', address: '' },
      MCD_JOIN_USDT_A: { name: 'MCD_JOIN_USDT_A', address: '' },
      MCD_JOIN_PAXUSD_A: { name: 'MCD_JOIN_PAXUSD_A', address: '' },
      MCD_JOIN_PSM_PAX_A: { name: 'MCD_JOIN_PSM_PAX_A', address: '' },
      MCD_JOIN_COMP_A: { name: 'MCD_JOIN_COMP_A', address: '' },
      MCD_JOIN_LRC_A: { name: 'MCD_JOIN_LRC_A', address: '' },
      MCD_JOIN_LINK_A: { name: 'MCD_JOIN_LINK_A', address: '' },
      MCD_JOIN_BAL_A: { name: 'MCD_JOIN_BAL_A', address: '' },
      MCD_JOIN_YFI_A: { name: 'MCD_JOIN_YFI_A', address: '' },
      MCD_JOIN_GUSD_A: { name: 'MCD_JOIN_GUSD_A', address: '' },
      MCD_JOIN_PSM_GUSD_A: { name: 'MCD_JOIN_PSM_GUSD_A', address: '' },
      MCD_JOIN_UNI_A: { name: 'MCD_JOIN_UNI_A', address: '' },
      MCD_JOIN_RENBTC_A: { name: 'MCD_JOIN_RENBTC_A', address: '' },
      MCD_JOIN_AAVE_A: { name: 'MCD_JOIN_AAVE_A', address: '' },
      MCD_JOIN_MATIC_A: { name: 'MCD_JOIN_MATIC_A', address: '' },
      MCD_JOIN_WSTETH_A: { name: 'MCD_JOIN_WSTETH_A', address: '' },
      MCD_JOIN_WSTETH_B: { name: 'MCD_JOIN_WSTETH_B', address: '' },
      MCD_JOIN_UNIV2DAIETH_A: { name: 'MCD_JOIN_UNIV2DAIETH_A', address: '' },
      MCD_JOIN_UNIV2WBTCETH_A: { name: 'MCD_JOIN_UNIV2WBTCETH_A', address: '' },
      MCD_JOIN_UNIV2USDCETH_A: { name: 'MCD_JOIN_UNIV2USDCETH_A', address: '' },
      MCD_JOIN_UNIV2DAIUSDC_A: { name: 'MCD_JOIN_UNIV2DAIUSDC_A', address: '' },
      MCD_JOIN_UNIV2ETHUSDT_A: { name: 'MCD_JOIN_UNIV2ETHUSDT_A', address: '' },
      MCD_JOIN_UNIV2LINKETH_A: { name: 'MCD_JOIN_UNIV2LINKETH_A', address: '' },
      MCD_JOIN_UNIV2UNIETH_A: { name: 'MCD_JOIN_UNIV2UNIETH_A', address: '' },
      MCD_JOIN_UNIV2WBTCDAI_A: { name: 'MCD_JOIN_UNIV2WBTCDAI_A', address: '' },
      MCD_JOIN_UNIV2AAVEETH_A: { name: 'MCD_JOIN_UNIV2AAVEETH_A', address: '' },
      MCD_JOIN_UNIV2DAIUSDT_A: { name: 'MCD_JOIN_UNIV2DAIUSDT_A', address: '' },
      MCD_JOIN_RWA001_A: { name: 'MCD_JOIN_RWA001_A', address: '' },
      MCD_JOIN_RWA002_A: { name: 'MCD_JOIN_RWA002_A', address: '' },
      MCD_JOIN_RWA003_A: { name: 'MCD_JOIN_RWA003_A', address: '' },
      MCD_JOIN_RWA004_A: { name: 'MCD_JOIN_RWA004_A', address: '' },
      MCD_JOIN_RWA005_A: { name: 'MCD_JOIN_RWA005_A', address: '' },
      MCD_JOIN_RWA006_A: { name: 'MCD_JOIN_RWA006_A', address: '' },
      MCD_JOIN_RETH_A: { name: 'MCD_JOIN_RETH_A', address: '' },
      MCD_JOIN_GNO_A: { name: 'MCD_JOIN_GNO_A', address: '' },
      MCD_JOIN_DIRECT_AAVEV2_DAI: { name: 'MCD_JOIN_DIRECT_AAVEV2_DAI', address: '' },
      MCD_JOIN_GUNIV3DAIUSDC1_A: { name: 'MCD_JOIN_GUNIV3DAIUSDC1_A', address: '' },
      MCD_JOIN_GUNIV3DAIUSDC2_A: { name: 'MCD_JOIN_GUNIV3DAIUSDC2_A', address: '' },
      MCD_JOIN_CRVV1ETHSTETH_A: { name: 'MCD_JOIN_CRVV1ETHSTETH_A', address: '' },
    },
    pips: {
      PIP_ETH: { name: 'PIP_ETH', address: '' },
      PIP_BAT: { name: 'PIP_BAT', address: '' },
      PIP_USDC: { name: 'PIP_USDC', address: '' },
      PIP_WBTC: { name: 'PIP_WBTC', address: '' },
      PIP_TUSD: { name: 'PIP_TUSD', address: '' },
      PIP_ZRX: { name: 'PIP_ZRX', address: '' },
      PIP_KNC: { name: 'PIP_KNC', address: '' },
      PIP_MANA: { name: 'PIP_MANA', address: '' },
      PIP_USDT: { name: 'PIP_USDT', address: '' },
      PIP_PAXUSD: { name: 'PIP_PAXUSD', address: '' },
      PIP_PAX: { name: 'PIP_PAX', address: '' },
      PIP_COMP: { name: 'PIP_COMP', address: '' },
      PIP_LRC: { name: 'PIP_LRC', address: '' },
      PIP_LINK: { name: 'PIP_LINK', address: '' },
      PIP_BAL: { name: 'PIP_BAL', address: '' },
      PIP_YFI: { name: 'PIP_YFI', address: '' },
      PIP_GUSD: { name: 'PIP_GUSD', address: '' },
      PIP_UNI: { name: 'PIP_UNI', address: '' },
      PIP_RENBTC: { name: 'PIP_RENBTC', address: '' },
      PIP_AAVE: { name: 'PIP_AAVE', address: '' },
      PIP_MATIC: { name: 'PIP_MATIC', address: '' },
      PIP_WSTETH: { name: 'PIP_WSTETH', address: '' },
      PIP_ADAI: { name: 'PIP_ADAI', address: '' },
      PIP_UNIV2DAIETH: { name: 'PIP_UNIV2DAIETH', address: '' },
      PIP_UNIV2WBTCETH: { name: 'PIP_UNIV2WBTCETH', address: '' },
      PIP_UNIV2USDCETH: { name: 'PIP_UNIV2USDCETH', address: '' },
      PIP_UNIV2DAIUSDC: { name: 'PIP_UNIV2DAIUSDC', address: '' },
      PIP_UNIV2ETHUSDT: { name: 'PIP_UNIV2ETHUSDT', address: '' },
      PIP_UNIV2LINKETH: { name: 'PIP_UNIV2LINKETH', address: '' },
      PIP_UNIV2UNIETH: { name: 'PIP_UNIV2UNIETH', address: '' },
      PIP_UNIV2WBTCDAI: { name: 'PIP_UNIV2WBTCDAI', address: '' },
      PIP_UNIV2AAVEETH: { name: 'PIP_UNIV2AAVEETH', address: '' },
      PIP_UNIV2DAIUSDT: { name: 'PIP_UNIV2DAIUSDT', address: '' },
      PIP_GUNIV3DAIUSDC1: { name: 'PIP_GUNIV3DAIUSDC1', address: '' },
      PIP_GUNIV3DAIUSDC2: { name: 'PIP_GUNIV3DAIUSDC2', address: '' },
      PIP_CRVV1ETHSTETH: { name: 'PIP_CRVV1ETHSTETH', address: '' },
      PIP_RWA001: { name: 'PIP_RWA001', address: '' },
      PIP_RWA002: { name: 'PIP_RWA002', address: '' },
      PIP_RWA003: { name: 'PIP_RWA003', address: '' },
      PIP_RWA004: { name: 'PIP_RWA004', address: '' },
      PIP_RWA005: { name: 'PIP_RWA005', address: '' },
      PIP_RWA006: { name: 'PIP_RWA006', address: '' },
      PIP_RETH: { name: 'PIP_RETH', address: '' },
      PIP_GNO: { name: 'PIP_GNO', address: '' },
      PIP_WETH: { name: 'PIP_WETH', address: '' },
    },
  },
  automation: {
    AutomationBot: { name: 'AutomationBot', address: '' },
    AutomationBotV2: { name: 'AutomationBotV2', address: '' },
    AutomationBotAggregator: { name: 'AutomationBotAggregator', address: '' },
  },
  ajna: {
    AjnaPoolInfo: {
      name: 'AjnaPoolInfo',
      address: ADDRESS_ZERO,
      serviceRegistryName: SERVICE_REGISTRY_NAMES.ajna.AJNA_POOL_UTILS_INFO,
    },
    AjnaProxyActions: {
      name: 'AjnaProxyActions',
      address: ADDRESS_ZERO,
    },
    AjnaPoolPairs_ETHDAI: {
      name: 'AjnaPoolPairs_ETHDAI',
      address: ADDRESS_ZERO,
    },
    AjnaPoolPairs_ETHUSDC: {
      name: 'AjnaPoolPairs_ETHUSDC',
      address: ADDRESS_ZERO,
    },
    AjnaPoolPairs_RETHDAI: {
      name: 'AjnaPoolPairs_RETHDAI',
      address: ADDRESS_ZERO,
    },
    AjnaPoolPairs_RETHETH: {
      name: 'AjnaPoolPairs_RETHETH',
      address: ADDRESS_ZERO,
    },
    AjnaPoolPairs_RETHUSDC: {
      name: 'AjnaPoolPairs_RETHUSDC',
      address: ADDRESS_ZERO,
    },
    AjnaPoolPairs_USDCETH: {
      name: 'AjnaPoolPairs_USDCETH',
      address: ADDRESS_ZERO,
    },
    AjnaPoolPairs_USDCDAI: {
      name: 'AjnaPoolPairs_USDCDAI',
      address: ADDRESS_ZERO,
    },
    AjnaPoolPairs_USDCWBTC: {
      name: 'AjnaPoolPairs_USDCWBTC',
      address: ADDRESS_ZERO,
    },
    AjnaPoolPairs_WBTCDAI: {
      name: 'AjnaPoolPairs_WBTCDAI',
      address: ADDRESS_ZERO,
    },
    AjnaPoolPairs_WBTCUSDC: {
      name: 'AjnaPoolPairs_WBTCUSDC',
      address: ADDRESS_ZERO,
    },
    AjnaPoolPairs_WSTETHDAI: {
      name: 'AjnaPoolPairs_WSTETHDAI',
      address: ADDRESS_ZERO,
    },
    AjnaPoolPairs_WSTETHETH: {
      name: 'AjnaPoolPairs_WSTETHETH',
      address: ADDRESS_ZERO,
    },
    AjnaPoolPairs_WSTETHUSDC: {
      name: 'AjnaPoolPairs_WSTETHUSDC',
      address: ADDRESS_ZERO,
    },
    AjnaPoolPairs_CBETHETH: {
      name: 'AjnaPoolPairs_CBETHETH',
      address: ADDRESS_ZERO,
    },
    AjnaPoolPairs_TBTCWBTC: {
      name: 'AjnaPoolPairs_TBTCWBTC',
      address: ADDRESS_ZERO,
    },
    AjnaPoolPairs_TBTCUSDC: {
      name: 'AjnaPoolPairs_TBTCUSDC',
      address: ADDRESS_ZERO,
    },
    AjnaPoolPairs_ETHGHO: {
      name: 'AjnaPoolPairs_ETHGHO',
      address: ADDRESS_ZERO,
    },
    AjnaPoolPairs_WSTETHGHO: {
      name: 'AjnaPoolPairs_WSTETHGHO',
      address: ADDRESS_ZERO,
    },
    AjnaPoolPairs_GHODAI: {
      name: 'AjnaPoolPairs_GHODAI',
      address: ADDRESS_ZERO,
    },
    AjnaPoolPairs_RETHGHO: {
      name: 'AjnaPoolPairs_RETHGHO',
      address: ADDRESS_ZERO,
    },
    AjnaPoolPairs_WBTCGHO: {
      name: 'AjnaPoolPairs_WBTCGHO',
      address: ADDRESS_ZERO,
    },
    AjnaPoolPairs_CBETHGHO: {
      name: 'AjnaPoolPairs_CBETHGHO',
      address: ADDRESS_ZERO,
    },
    AjnaPoolPairs_WLDUSDC: {
      name: 'AjnaPoolPairs_WLDUSDC',
      address: ADDRESS_ZERO,
    },
    AjnaPoolPairs_USDCWLD: {
      name: 'AjnaPoolPairs_USDCWLD',
      address: ADDRESS_ZERO,
    },
    AjnaPoolPairs_SDAIUSDC: {
      name: 'AjnaPoolPairs_SDAIUSDC',
      address: ADDRESS_ZERO,
    },
    AjnaPoolPairs_YFIDAI: {
      name: 'AjnaPoolPairs_YFIDAI',
      address: ADDRESS_ZERO,
    },
    AjnaPoolPairs_YIELDETHETH: {
      name: 'AjnaPoolPairs_YIELDETHETH',
      address: ADDRESS_ZERO,
    },
    AjnaPoolPairs_YIELDBTCWBTC: {
      name: 'AjnaPoolPairs_YIELDBTCWBTC',
      address: ADDRESS_ZERO,
    },
    AjnaRewardsManager: {
      name: 'AjnaRewardsManager',
      address: ADDRESS_ZERO,
    },
    AjnaRewardsClaimer: {
      name: 'AjnaRewardsClaimer',
      address: ADDRESS_ZERO,
    },
    ERC20PoolFactory: {
      name: 'ERC20PoolFactory',
      address: '0x0000000000000000000000000000000000000000',
      serviceRegistryName: SERVICE_REGISTRY_NAMES.ajna.ERC20_POOL_FACTORY,
    },
  },
  morphoblue: {
    MorphoBlue: {
      name: 'MorphoBlue',
      address: '0x0000000000000000000000000000000000000000',
      serviceRegistryName: SERVICE_REGISTRY_NAMES.morphoblue.MORPHO_BLUE,
    },
  },
}
