/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as views from "./views";
export type { views };
export type { OperationExecutor } from "./OperationExecutor";
export type { OperationStorage } from "./OperationStorage";
export type { OperationsRegistry } from "./OperationsRegistry";
export type { ServiceRegistry } from "./ServiceRegistry";
