// Service Registry Entry Names
export const SERVICE_REGISTRY_NAMES = {
  common: {
    PULL_TOKEN: 'PullToken_3',
    SEND_TOKEN: 'SendToken_4',
    SET_APPROVAL: 'SetApproval_3',
    TAKE_A_FLASHLOAN: 'TakeFlashloan_3',
    SWAP_ACTION: 'SwapAction_3',
    WRAP_ETH: 'WrapEth_3',
    UNWRAP_ETH: 'UnwrapEth_3',
    RETURN_FUNDS: 'ReturnFunds_3',
    POSITION_CREATED: 'PositionCreated',
    ACCOUNT_GUARD: 'AccountGuard',
    ACCOUNT_FACTORY: 'AccountFactory',
    OPERATION_EXECUTOR: 'OperationExecutor_2',
    OPERATION_STORAGE: 'OperationStorage_2',
    OPERATIONS_REGISTRY: 'OperationsRegistry_2',
    CHAINLOG_VIEWER: 'ChainLogView',
    ONE_INCH_AGGREGATOR: 'OneInchAggregator',
    DS_GUARD_FACTORY: 'DSGuardFactory',
    DS_PROXY_REGISTRY: 'DSProxyRegistry',
    DS_PROXY_FACTORY: 'DSProxyFactory',
    SWAP: 'Swap',
    EXCHANGE: 'Exchange',
    UNISWAP_ROUTER: 'UniswapRouter',
    BALANCER_VAULT: 'BalancerVault',
    SERVICE_REGISTRY: 'ServiceRegistry',
    WETH: 'WETH',
    DAI: 'DAI',
    USDC: 'USDC',
    STETH: 'STETH',
    WSTETH: 'WSTETH',
    WBTC: 'WBTC',
  },
  aave: {
    v2: {
      DEPOSIT: 'AaveDeposit_3',
      WITHDRAW: 'AaveWithdraw_3',
      BORROW: 'AaveBorrow_3',
      PAYBACK: 'AavePayback_3',
      LENDING_POOL: 'AaveLendingPool',
      WETH_GATEWAY: 'AaveWethGateway',
    },
    v3: {
      DEPOSIT: 'AaveV3Deposit',
      WITHDRAW: 'AaveV3Withdraw',
      BORROW: 'AaveV3Borrow',
      PAYBACK: 'AaveV3Payback',
      AAVE_POOL: 'AavePool',
      SET_EMODE: 'AaveV3SetEMode',
    },
    L2_ENCODER: 'AaveL2Encoder',
  },
  spark: {
    DEPOSIT: 'SparkDeposit',
    WITHDRAW: 'SparkWithdraw',
    BORROW: 'SparkBorrow',
    PAYBACK: 'SparkPayback',
    LENDING_POOL: 'SparkLendingPool',
    SET_EMODE: 'SparkSetEMode',
  },
  maker: {
    DEPOSIT: 'MakerDeposit',
    PAYBACK: 'MakerPayback',
    WITHDRAW: 'MakerWithdraw',
    GENERATE: 'MakerGenerate',
    OPEN_VAULT: 'MakerOpenVault',

    MCD_VIEW: 'McdView',
    FLASH_MINT_MODULE: 'McdFlashMintModule',
    MCD_MANAGER: 'McdManager',
    MCD_JUG: 'McdJug',
    MCD_JOIN_DAI: 'McdJoinDai',
    CDP_ALLOW: 'CdpAllow',
    CHAINLOG_VIEW: 'ChainLogView',
  },
  ajna: {
    DEPOSIT_BORROW: 'AjnaDepositBorrow',
    REPAY_WITHDRAW: 'AjnaRepayWithdraw',
    ERC20_POOL_FACTORY: 'ERC20PoolFactory',
    AJNA_POOL_UTILS_INFO: 'AjnaPoolUtilsInfo',
  },
  morphoblue: {
    MORPHO_BLUE: 'MorphoBlue',
    DEPOSIT: 'MorphoBlueDeposit',
    WITHDRAW: 'MorphoBlueWithdraw',
    BORROW: 'MorphoBlueBorrow',
    PAYBACK: 'MorphoBluePayback',
  },
  test: {
    DUMMY_ACTION: 'DummyAction',
    DUMMY_OPTIONAL_ACTION: 'DummyOptionalAction',
    DUMMY_SWAP: 'DummySwap',
    DUMMY_EXCHANGE: 'MockExchange',
    SWAP: 'uSwap',
  },
} as const

export type AllValues<T> = { [K in keyof T]: T[K] extends object ? AllValues<T[K]> : T[K] }[keyof T]

export type ContractNames = AllValues<typeof SERVICE_REGISTRY_NAMES>
