// Service Registry Entry Names
export const SERVICE_REGISTRY_NAMES = {
  common: {
    PULL_TOKEN: 'PullToken_4',
    SEND_TOKEN: 'SendToken_5',
    SET_APPROVAL: 'SetApproval_4',
    TAKE_A_FLASHLOAN: 'TakeFlashloan_4',
    TAKE_A_FLASHLOAN_BALANCER: 'TakeFlashloanBalancer',
    SWAP_ACTION: 'SwapAction_6',
    WRAP_ETH: 'WrapEth_4',
    UNWRAP_ETH: 'UnwrapEth_4',
    RETURN_FUNDS: 'ReturnFunds_4',
    POSITION_CREATED: 'PositionCreated',
    ACCOUNT_GUARD: 'AccountGuard',
    ACCOUNT_FACTORY: 'AccountFactory',
    OPERATION_EXECUTOR: 'OperationExecutor_3',
    OPERATION_STORAGE: 'OperationStorage_3',
    OPERATIONS_REGISTRY: 'OperationsRegistry_3',
    CHAINLOG_VIEWER: 'ChainLogView',
    ONE_INCH_AGGREGATOR: 'OneInchAggregator',
    ONE_INCH_AGGREGATOR5: 'OneInchAggregator5',
    DS_GUARD_FACTORY: 'DSGuardFactory',
    DS_PROXY_REGISTRY: 'DSProxyRegistry',
    DS_PROXY_FACTORY: 'DSProxyFactory',
    SWAP: 'Swap2',
    EXCHANGE: 'Exchange',
    UNISWAP_ROUTER: 'UniswapRouter',
    BALANCER_VAULT: 'BalancerVault',
    SERVICE_REGISTRY: 'ServiceRegistry',
    WETH: 'WETH',
    DAI: 'DAI',
    USDC: 'USDC',
    STETH: 'STETH',
    WSTETH: 'WSTETH',
    WBTC: 'WBTC',
  },
  aave: {
    v2: {
      DEPOSIT: 'AaveDeposit_3',
      WITHDRAW: 'AaveWithdraw_3',
      BORROW: 'AaveBorrow_3',
      PAYBACK: 'AavePayback_3',
      LENDING_POOL: 'AaveLendingPool',
      WETH_GATEWAY: 'AaveWethGateway',
    },
    v3: {
      DEPOSIT: 'AaveV3Deposit_2',
      WITHDRAW: 'AaveV3Withdraw_2',
      WITHDRAW_AUTO: 'AaveV3WithdrawAuto',
      BORROW: 'AaveV3Borrow_2',
      PAYBACK: 'AaveV3Payback_2',
      AAVE_POOL: 'AavePool',
      SET_EMODE: 'AaveV3SetEMode_2',
    },
    L2_ENCODER: 'AaveL2Encoder',
  },
  spark: {
    DEPOSIT: 'SparkDeposit',
    WITHDRAW: 'SparkWithdraw',
    BORROW: 'SparkBorrow',
    PAYBACK: 'SparkPayback',
    SPARK_LENDING_POOL: 'SparkLendingPool',
    SET_EMODE: 'SparkSetEMode',
  },
  maker: {
    DEPOSIT: 'MakerDeposit',
    PAYBACK: 'MakerPayback',
    WITHDRAW: 'MakerWithdraw',
    GENERATE: 'MakerGenerate',
    OPEN_VAULT: 'MakerOpenVault',

    MCD_VIEW: 'McdView',
    FLASH_MINT_MODULE: 'McdFlashMintModule',
    MCD_MANAGER: 'McdManager',
    MCD_JUG: 'McdJug',
    MCD_JOIN_DAI: 'McdJoinDai',
    CDP_ALLOW: 'CdpAllow',
    CHAINLOG_VIEW: 'ChainLogView',
  },
  ajna: {
    DEPOSIT_BORROW: 'AjnaDepositBorrow',
    REPAY_WITHDRAW: 'AjnaRepayWithdraw',
  },
  morphoblue: {
    MORPHO_BLUE: 'MorphoBlue',
  },
  test: {
    DUMMY_ACTION: 'DummyAction',
    DUMMY_OPTIONAL_ACTION: 'DummyOptionalAction',
    DUMMY_SWAP: 'DummySwap',
    DUMMY_EXCHANGE: 'DummyExchange',
    SWAP: 'uSwap',
  },
} as const
