import { CONTRACT_NAMES } from '@dma-deployments/constants'
import { SystemConfig } from '@dma-deployments/types/deployment-config'
import { constants } from 'ethers'

export const config: SystemConfig = {
  mpa: {
    core: {
      ServiceRegistry: {
        name: 'ServiceRegistry',
        deploy: false,
        address: '0x73024Ec24c03904A4b5FBfa249B410891C12407b',
        history: [],
        constructorArgs: [0],
      },
      OperationExecutor: {
        name: 'OperationExecutor',
        deploy: true,
        address: '',
        serviceRegistryName: 'OperationExecutor_2',
        history: [],
        constructorArgs: ['address:ServiceRegistry'],
      },
      OperationStorage: {
        name: 'OperationStorage',
        deploy: false,
        address: '',
        serviceRegistryName: 'OperationStorage_2',
        history: [],
        constructorArgs: ['address:ServiceRegistry', 'address:OperationExecutor'],
      },
      OperationsRegistry: {
        name: 'OperationsRegistry',
        deploy: false,
        address: '',
        serviceRegistryName: 'OperationsRegistry_2',
        history: [],
        constructorArgs: [],
      },
      DSProxyFactory: {
        name: 'DSProxyFactory',
        deploy: false,
        address: constants.AddressZero,
        serviceRegistryName: CONTRACT_NAMES.common.DS_PROXY_FACTORY,
        history: [],
        constructorArgs: [],
      },
      DSProxyRegistry: {
        name: 'DSProxyRegistry',
        deploy: false,
        address: constants.AddressZero,
        serviceRegistryName: CONTRACT_NAMES.common.DS_PROXY_REGISTRY,
        history: [],
        constructorArgs: ['address:DSProxyFactory'],
      },
      DSGuardFactory: {
        name: 'DSGuardFactory',
        deploy: false,
        address: constants.AddressZero,
        serviceRegistryName: CONTRACT_NAMES.common.DS_GUARD_FACTORY,
        history: [],
        constructorArgs: [],
      },
      AccountGuard: {
        name: 'AccountGuard',
        deploy: false,
        address: '',
        history: [],
        constructorArgs: [],
      },
      AccountFactory: {
        name: 'AccountFactory',
        deploy: false,
        address: '',
        history: [],
        constructorArgs: ['address:AccountGuard'],
      },
      Swap: {
        name: 'Swap',
        address: '',
        deploy: false,
        history: [],
      },
    },
    actions: {
      PositionCreated: {
        name: 'PositionCreated',
        deploy: true,
        address: '',
        serviceRegistryName: 'PositionCreated',
        history: [],
        constructorArgs: [],
      },
      SwapAction: {
        name: 'SwapAction',
        deploy: true,
        address: '',
        serviceRegistryName: 'SwapAction_3',
        history: [],
        constructorArgs: ['address:ServiceRegistry'],
      },
      TakeFlashloan: {
        name: 'TakeFlashloan',
        deploy: true,
        address: '',
        serviceRegistryName: 'TakeFlashloan_3',
        history: [],
        constructorArgs: ['address:ServiceRegistry', '0x6B175474E89094C44Da98b954EedeAC495271d0F'],
      },
      SetApproval: {
        name: 'SetApproval',
        deploy: true,
        address: '',
        serviceRegistryName: 'SetApproval_3',
        history: [],
        constructorArgs: ['address:ServiceRegistry'],
      },
      PullToken: {
        name: 'PullToken',
        deploy: true,
        address: '',
        serviceRegistryName: 'PullToken_3',
        history: [],
        constructorArgs: [],
      },
      SendToken: {
        name: 'SendToken',
        deploy: true,
        address: '',
        serviceRegistryName: 'SendToken_4',
        history: [],
        constructorArgs: ['address:ServiceRegistry'],
      },
      WrapEth: {
        name: 'WrapEth',
        deploy: true,
        address: '',
        serviceRegistryName: 'WrapEth_3',
        history: [],
        constructorArgs: ['address:ServiceRegistry'],
      },
      UnwrapEth: {
        name: 'UnwrapEth',
        deploy: true,
        address: '',
        serviceRegistryName: 'UnwrapEth_3',
        history: [],
        constructorArgs: ['address:ServiceRegistry'],
      },
      ReturnFunds: {
        name: 'ReturnFunds',
        deploy: true,
        address: '',
        serviceRegistryName: 'ReturnFunds_3',
        history: [],
        constructorArgs: [],
      },
      AaveBorrow: {
        name: 'AaveBorrow',
        deploy: true,
        address: '',
        serviceRegistryName: 'AaveBorrow_3',
        history: [],
        constructorArgs: ['address:ServiceRegistry'],
      },
      AaveWithdraw: {
        name: 'AaveWithdraw',
        deploy: true,
        address: '',
        serviceRegistryName: 'AaveWithdraw_3',
        history: [],
        constructorArgs: ['address:ServiceRegistry'],
      },
      AaveDeposit: {
        name: 'AaveDeposit',
        deploy: true,
        address: '',
        serviceRegistryName: 'AaveDeposit_3',
        history: [],
        constructorArgs: ['address:ServiceRegistry'],
      },
      AavePayback: {
        name: 'AavePayback',
        deploy: true,
        address: '',
        serviceRegistryName: 'AavePayback_3',
        history: [],
        constructorArgs: ['address:ServiceRegistry'],
      },
      AaveV3Borrow: {
        name: 'AaveV3Borrow',
        deploy: false,
        address: '0x18ca8bE41D32727383bC0F98705f7662ed0B7E28',
        serviceRegistryName: 'AaveV3Borrow',
        history: [],
        constructorArgs: ['address:ServiceRegistry'],
      },
      AaveV3Withdraw: {
        name: 'AaveV3Withdraw',
        deploy: false,
        address: '',
        serviceRegistryName: 'AaveV3Withdraw',
        history: [],
        constructorArgs: ['address:ServiceRegistry'],
      },
      AaveV3Deposit: {
        name: 'AaveV3Deposit',
        deploy: false,
        address: '0x852c56859840487DcED2aF501fC06f7462C4f2a8',
        serviceRegistryName: 'AaveV3Deposit',
        history: [],
        constructorArgs: ['address:ServiceRegistry'],
      },
      AaveV3Payback: {
        name: 'AaveV3Payback',
        deploy: false,
        address: '0xdB736d13CE851Ee81ac2109DF37EBAb8Ce525C42',
        serviceRegistryName: 'AaveV3Payback',
        history: [],
        constructorArgs: ['address:ServiceRegistry'],
      },
      AaveV3SetEMode: {
        name: 'AaveV3SetEMode',
        deploy: false,
        address: '0xd4DB3799DEe98Fe752d952Ba6F84Bb99Af829920',
        serviceRegistryName: 'AaveV3SetEMode',
        history: [],
        constructorArgs: ['address:ServiceRegistry'],
      },
    },
  },
  common: {
    GnosisSafe: {
      name: 'GnosisSafe',
      address: '0x41A92d82D70005B55070dB7138b21d7c28F27CC0',
    },
    UniswapRouterV3: {
      name: 'UniswapRouterV3',
      address: '0xe592427a0aece92de3edee1f18e0157c05861564',
      serviceRegistryName: CONTRACT_NAMES.common.UNISWAP_ROUTER,
    },
    BalancerVault: {
      name: 'BalancerVault',
      address: '0xBA12222222228d8Ba445958a75a0704d566BF2C8',
      serviceRegistryName: CONTRACT_NAMES.common.BALANCER_VAULT,
    },
    OneInchAggregator: {
      name: 'OneInchAggregator',
      address: '0x1111111254fb6c44bac0bed2854e76f90643097d',
      serviceRegistryName: CONTRACT_NAMES.common.ONE_INCH_AGGREGATOR,
    },
    AuthorizedCaller: {
      name: 'AuthorizedCaller',
      address: '0x85f9b7408afE6CEb5E46223451f5d4b832B522dc',
    },
    FeeRecipient: {
      name: 'FeeRecipient',
      address: '0xC7b548AD9Cf38721810246C079b2d8083aba8909',
    },
    MerkleRedeemer: {
      name: 'MerkleRedeemer',
      address: constants.AddressZero,
    },
    DssCharter: {
      name: 'DssCharter',
      address: constants.AddressZero,
    },
    DssProxyActions: {
      name: 'DssProxyActions',
      address: constants.AddressZero,
    },
    DssProxyActionsCharter: {
      name: 'DssProxyActionsCharter',
      address: constants.AddressZero,
    },
    DssMultiplyProxyActions: {
      name: 'DssMultiplyProxyActions',
      address: constants.AddressZero,
    },
    DssCropper: {
      name: 'DssCropper',
      address: constants.AddressZero,
    },
    DssProxyActionsCropjoin: {
      name: 'DssProxyActionsCropjoin',
      address: constants.AddressZero,
    },
    DssProxyActionsDsr: {
      name: 'DssProxyActionsDsr',
      address: constants.AddressZero,
    },
    Otc: {
      name: 'Otc',
      address: constants.AddressZero,
    },
    OtcSupportMethods: {
      name: 'OtcSupportMethods',
      address: constants.AddressZero,
    },
    ServiceRegistry: {
      name: 'ServiceRegistry',
      address: constants.AddressZero,
    },
    GuniProxyActions: {
      name: 'GuniProxyActions',
      address: constants.AddressZero,
    },
    GuniResolver: {
      name: 'GuniResolver',
      address: constants.AddressZero,
    },
    GuniRouter: {
      name: 'GuniRouter',
      address: constants.AddressZero,
    },
    CdpRegistry: {
      name: 'CdpRegistry',
      address: constants.AddressZero,
    },
    DefaultExchange: {
      name: 'DefaultExchange',
      address: constants.AddressZero,
    },
    NoFeesExchange: {
      name: 'NoFeesExchange',
      address: constants.AddressZero,
    },
    LowerFeesExchange: {
      name: 'LowerFeesExchange',
      address: constants.AddressZero,
    },
    LidoCrvLiquidityFarmingReward: {
      name: 'LidoCrvLiquidityFarmingReward',
      address: constants.AddressZero,
    },
    ChainlinkPriceOracle_USDCUSD: {
      name: 'ChainlinkPriceOracle_USDCUSD',
      address: constants.AddressZero,
    },
    ChainlinkPriceOracle_ETHUSD: {
      name: 'ChainlinkPriceOracle_ETHUSD',
      address: constants.AddressZero,
    },
    ADAI: { name: 'ADAI', address: constants.AddressZero },
    AAVE: { name: 'AAVE', address: '0x251661BB7C6869165eF35810E5e1D25Ed57be2Fe' },
    BAL: { name: 'BAL', address: '0x8c6e73CA229AB3933426aDb5cc829c1E4928551d' },
    BAT: { name: 'BAT', address: '0x75645f86e90a1169e697707C813419977ea26779' },
    COMP: { name: 'COMP', address: '0x8032dce0b793C21B8F7B648C01224c3b557271ED' },
    CRVV1ETHSTETH: { name: 'CRVV1ETHSTETH', address: constants.AddressZero },
    DAI: {
      name: 'DAI',
      address: '0xDA10009cBd5D07dd0CeCc66161FC93D7c9000da1',
      serviceRegistryName: 'DAI',
    },
    ETH: { name: 'ETH', address: '0xB4FBF271143F4FBf7B91A5ded31805e42b2208d6' },
    GNO: { name: 'GNO', address: '0x86Bc432064d7F933184909975a384C7E4c9d0977' },
    GUNIV3DAIUSDC1: {
      name: 'GUNIV3DAIUSDC1',
      address: constants.AddressZero,
    },
    GUNIV3DAIUSDC2: {
      name: 'GUNIV3DAIUSDC2',
      address: constants.AddressZero,
    },
    GUSD: { name: 'GUSD', address: '0x67aeF79654D8F6CF44FdC08949c308a4F6b3c45B' },
    KNC: { name: 'KNC', address: '0x9A58801cf901486Df9323bcE83A7684915DBAE54' },
    LDO: { name: 'LDO', address: constants.AddressZero },
    LINK: { name: 'LINK', address: '0x4724A967A4F7E42474Be58AbdF64bF38603422FF' },
    LRC: { name: 'LRC', address: '0xe32aC5b19051728421A8F4A8a5757D0e127a14F6' },
    MANA: { name: 'MANA', address: '0x347fceA8b4fD1a46e2c0DB8F79e22d293c2F8513' },
    MATIC: { name: 'MATIC', address: '0x5B3b6CF665Cc7B4552F4347623a2A9E00600CBB5' },
    PAX: { name: 'PAX', address: '0x4547863912Fe2d17D3827704138957a8317E8dCD' },
    PAXUSD: { name: 'PAXUSD', address: '0x4547863912Fe2d17D3827704138957a8317E8dCD' },
    RENBTC: { name: 'RENBTC', address: '0x30d0A215aef6DadA4771a2b30a59B842f969EfD4' },
    RETH: { name: 'RETH', address: '0x62bc478ffc429161115a6e4090f819ce5c50a5d9' },
    RWA001: { name: 'RWA001', address: '0xeb7C7DE82c3b05BD4059f11aE8f43dD7f1595bce' },
    RWA002: { name: 'RWA002', address: '0x09fE0aE289553010D6EcBdFF98cc9C08030dE3b8' },
    RWA003: { name: 'RWA003', address: '0x5cf15Cc2710aFc0EaBBD7e045f84F9556B204331' },
    RWA004: { name: 'RWA004', address: '0xA7fbA77c4d18e12d1F385E2dcFfb377c9dBD91d2' },
    RWA005: { name: 'RWA005', address: '0x650d168fC94B79Bb16898CAae773B0Ce1097Cc3F' },
    RWA006: { name: 'RWA006', address: '0xf754FD6611852eE94AC0614c51B8692cAE9fEe9F' },
    STETH: { name: 'STETH', address: '0x1643E812aE58766192Cf7D2Cf9567dF2C37e9B7F' },
    TUSD: { name: 'TUSD', address: '0xe0B3D300E2e09c1Fd01252287dDbC70A7730ffB0' },
    UNI: { name: 'UNI', address: '0x82D98aA89E391c6759012df39ccDA0d9d6b24143' },
    UNIV2AAVEETH: { name: 'UNIV2AAVEETH', address: '0xaF2CC6F46d1d0AB30dd45F59B562394c3E21e6f3' },
    UNIV2DAIETH: { name: 'UNIV2DAIETH', address: '0x5dD9dec52a16d4d1Df10a66ac71d4731c9Dad984' },
    UNIV2DAIUSDC: { name: 'UNIV2DAIUSDC', address: '0x260719B2ef507A86116FC24341ff0994F2097D42' },
    UNIV2DAIUSDT: { name: 'UNIV2DAIUSDT', address: '0xBF2C9aBbEC9755A0b6144051E19c6AD4e6fd6D71' },
    UNIV2ETHUSDT: { name: 'UNIV2ETHUSDT', address: '0xfcB32e1C4A4F1C820c9304B5CFfEDfB91aE2321C' },
    UNIV2LINKETH: { name: 'UNIV2LINKETH', address: '0x3361fB8f923D1Aa1A45B2d2eD4B8bdF313a3dA0c' },
    UNIV2UNIETH: { name: 'UNIV2UNIETH', address: '0xB80A38E50B2990Ac83e46Fe16631fFBb94F2780b' },
    UNIV2USDCETH: { name: 'UNIV2USDCETH', address: '0xD90313b3E43D9a922c71d26a0fBCa75A01Bb3Aeb' },
    UNIV2WBTCDAI: { name: 'UNIV2WBTCDAI', address: '0x3f78Bd3980c49611E5FA885f25Ca3a5fCbf0d7A0' },
    UNIV2WBTCETH: { name: 'UNIV2WBTCETH', address: '0x7883a92ac3e914F3400e8AE6a2FF05E6BA4Bd403' },
    USDC: {
      name: 'USDC',
      address: '0x7F5c764cBc14f9669B88837ca1490cCa17c31607',
      serviceRegistryName: 'USDC',
    },
    USDT: { name: 'USDT', address: '0x5858f25cc225525A7494f76d90A6549749b3030B' },
    WBTC: {
      name: 'WBTC',
      address: '0x68f180fcce6836688e9084f035309e29bf0a2095',
      serviceRegistryName: 'WBTC',
    },
    WETH: {
      name: 'WETH',
      address: '0x4200000000000000000000000000000000000006',
      serviceRegistryName: 'WETH',
    },
    WSTETH: {
      name: 'WSTETH',
      address: '0x1F32b1c2345538c0c6f582fCB022739c4A194Ebb',
      serviceRegistryName: 'WSTETH',
    },
    YFI: { name: 'YFI', address: '0xd9510EF268F8273C9b7514F0bfFe18Fe1EFC0d43' },
    ZRX: { name: 'ZRX', address: '0x96E0C18524789ED3e62CD9F56aAEc7cEAC78725a' },
  },
  aave: {
    v3: {
      AaveOracle: {
        name: 'AaveOracle',
        address: constants.AddressZero,
      },
      Pool: {
        name: 'Pool',
        address: constants.AddressZero,
        serviceRegistryName: CONTRACT_NAMES.aave.v3.AAVE_POOL,
      },
      AaveProtocolDataProvider: {
        name: 'AaveProtocolDataProvider',
        address: constants.AddressZero,
      },
    },
  },
  maker: {
    FlashMintModule: {
      name: 'FlashMintModule',
      address: '0x60744434d6339a6B27d73d9Eda62b6F66a0a04FA',
      serviceRegistryName: CONTRACT_NAMES.maker.FLASH_MINT_MODULE,
    },
    Chainlog: {
      name: 'Chainlog',
      address: constants.AddressZero,
    },
    CdpManager: {
      name: 'CdpManager',
      address: constants.AddressZero,
    },
    GetCdps: {
      name: 'CdpManager',
      address: constants.AddressZero,
    },
    Jug: {
      name: 'Jug',
      address: constants.AddressZero,
    },
    Pot: {
      name: 'Pot',
      address: constants.AddressZero,
    },
    End: {
      name: 'End',
      address: constants.AddressZero,
    },
    Spot: {
      name: 'Spot',
      address: constants.AddressZero,
    },
    Dog: {
      name: 'Dog',
      address: constants.AddressZero,
    },
    Vat: {
      name: 'Vat',
      address: constants.AddressZero,
    },
    McdGov: {
      name: 'McdGov',
      address: constants.AddressZero,
    },
    JoinDAI: {
      name: 'JoinDAI',
      address: constants.AddressZero,
    },
    JoinETH_A: {
      name: 'JoinETH_A',
      address: constants.AddressZero,
    },
    PipWETH: {
      name: 'PipWETH',
      address: constants.AddressZero,
    },
    PipLINK: {
      name: 'PipLINK',
      address: constants.AddressZero,
    },
  },
  automation: {
    AutomationBot: {
      name: 'AutomationBot',
      address: constants.AddressZero,
    },
    AutomationBotV2: {
      name: 'AutomationBotV2',
      address: constants.AddressZero,
    },
    AutomationBotAggregator: {
      name: 'AutomationBotAggregator',
      address: constants.AddressZero,
    },
  },
  ajna: {
    AjnaPoolInfo: {
      name: 'AjnaPoolInfo',
      address: constants.AddressZero,
    },
    AjnaProxyActions: {
      name: 'AjnaProxyActions',
      address: constants.AddressZero,
    },
    AjnaPoolPairs_WBTCUSDC: {
      name: 'AjnaPoolPairs_WBTCUSDC',
      address: constants.AddressZero,
    },
    AjnaPoolPairs_ETHUSDC: {
      name: 'AjnaPoolPairs_ETHUSDC',
      address: constants.AddressZero,
    },
    AjnaRewardsManager: {
      name: 'AjnaRewardsManager',
      address: constants.AddressZero,
    },
    AjnaRewardsClaimer: {
      name: 'AjnaRewardsClaimer',
      address: constants.AddressZero,
    },
  },
}
