import { CONTRACT_NAMES } from '@dma-deployments/constants/contract-names'
import { SystemConfig } from '@dma-deployments/types/deployment-config'
import { constants } from 'ethers'

export const config: SystemConfig = {
  mpa: {
    core: {
      ServiceRegistry: {
        name: 'ServiceRegistry',
        deploy: false,
        address: '0x73024Ec24c03904A4b5FBfa249B410891C12407b',
        history: [],
        constructorArgs: [0],
      },
      OperationExecutor: {
        name: 'OperationExecutor',
        deploy: true,
        address: '',
        serviceRegistryName: 'OperationExecutor_2',
        history: [],
        constructorArgs: ['address:ServiceRegistry'],
      },
      OperationStorage: {
        name: 'OperationStorage',
        deploy: false,
        address: '',
        serviceRegistryName: 'OperationStorage_2',
        history: [],
        constructorArgs: ['address:ServiceRegistry', 'address:OperationExecutor'],
      },
      OperationsRegistry: {
        name: 'OperationsRegistry',
        deploy: false,
        address: '',
        serviceRegistryName: 'OperationsRegistry_2',
        history: [],
        constructorArgs: [],
      },
      DSProxyFactory: {
        name: 'DSProxyFactory',
        deploy: false,
        address: constants.AddressZero,
        serviceRegistryName: CONTRACT_NAMES.common.DS_PROXY_FACTORY,
        history: [],
        constructorArgs: [],
      },
      DSProxyRegistry: {
        name: 'DSProxyRegistry',
        deploy: false,
        address: constants.AddressZero,
        serviceRegistryName: CONTRACT_NAMES.common.DS_PROXY_REGISTRY,
        history: [],
        constructorArgs: ['address:DSProxyFactory'],
      },
      DSGuardFactory: {
        name: 'DSGuardFactory',
        deploy: false,
        address: constants.AddressZero,
        serviceRegistryName: CONTRACT_NAMES.common.DS_GUARD_FACTORY,
        history: [],
        constructorArgs: [],
      },
      AccountGuard: {
        name: 'AccountGuard',
        deploy: false,
        address: '',
        history: [],
        constructorArgs: [],
      },
      AccountFactory: {
        name: 'AccountFactory',
        deploy: false,
        address: '',
        history: [],
        constructorArgs: ['address:AccountGuard'],
      },
    },
    actions: {
      PositionCreated: {
        name: 'PositionCreated',
        deploy: true,
        address: '',
        serviceRegistryName: 'PositionCreated',
        history: [],
        constructorArgs: [],
      },
      SwapAction: {
        name: 'SwapAction',
        deploy: true,
        address: '',
        serviceRegistryName: 'SwapAction_3',
        history: [],
        constructorArgs: ['address:ServiceRegistry'],
      },
      TakeFlashloan: {
        name: 'TakeFlashloan',
        deploy: true,
        address: '',
        serviceRegistryName: 'TakeFlashloan_3',
        history: [],
        constructorArgs: ['address:ServiceRegistry', '0x6B175474E89094C44Da98b954EedeAC495271d0F'],
      },
      SetApproval: {
        name: 'SetApproval',
        deploy: true,
        address: '',
        serviceRegistryName: 'SetApproval_3',
        history: [],
        constructorArgs: ['address:ServiceRegistry'],
      },
      PullToken: {
        name: 'PullToken',
        deploy: true,
        address: '',
        serviceRegistryName: 'PullToken_3',
        history: [],
        constructorArgs: [],
      },
      SendToken: {
        name: 'SendToken',
        deploy: true,
        address: '',
        serviceRegistryName: 'SendToken_4',
        history: [],
        constructorArgs: ['address:ServiceRegistry'],
      },
      WrapEth: {
        name: 'WrapEth',
        deploy: true,
        address: '',
        serviceRegistryName: 'WrapEth_3',
        history: [],
        constructorArgs: ['address:ServiceRegistry'],
      },
      UnwrapEth: {
        name: 'UnwrapEth',
        deploy: true,
        address: '',
        serviceRegistryName: 'UnwrapEth_3',
        history: [],
        constructorArgs: ['address:ServiceRegistry'],
      },
      ReturnFunds: {
        name: 'ReturnFunds',
        deploy: true,
        address: '',
        serviceRegistryName: 'ReturnFunds_3',
        history: [],
        constructorArgs: [],
      },
      AaveBorrow: {
        name: 'AaveBorrow',
        deploy: true,
        address: '',
        serviceRegistryName: 'AaveBorrow_3',
        history: [],
        constructorArgs: ['address:ServiceRegistry'],
      },
      AaveWithdraw: {
        name: 'AaveWithdraw',
        deploy: true,
        address: '',
        serviceRegistryName: 'AaveWithdraw_3',
        history: [],
        constructorArgs: ['address:ServiceRegistry'],
      },
      AaveDeposit: {
        name: 'AaveDeposit',
        deploy: true,
        address: '',
        serviceRegistryName: 'AaveDeposit_3',
        history: [],
        constructorArgs: ['address:ServiceRegistry'],
      },
      AavePayback: {
        name: 'AavePayback',
        deploy: true,
        address: '',
        serviceRegistryName: 'AavePayback_3',
        history: [],
        constructorArgs: ['address:ServiceRegistry'],
      },
      AaveV3Borrow: {
        name: 'AaveV3Borrow',
        deploy: false,
        address: '0x18ca8bE41D32727383bC0F98705f7662ed0B7E28',
        serviceRegistryName: 'AaveV3Borrow',
        history: [],
        constructorArgs: ['address:ServiceRegistry'],
      },
      AaveV3Withdraw: {
        name: 'AaveV3Withdraw',
        deploy: false,
        address: '',
        serviceRegistryName: 'AaveV3Withdraw',
        history: [],
        constructorArgs: ['address:ServiceRegistry'],
      },
      AaveV3Deposit: {
        name: 'AaveV3Deposit',
        deploy: false,
        address: '0x852c56859840487DcED2aF501fC06f7462C4f2a8',
        serviceRegistryName: 'AaveV3Deposit',
        history: [],
        constructorArgs: ['address:ServiceRegistry'],
      },
      AaveV3Payback: {
        name: 'AaveV3Payback',
        deploy: false,
        address: '0xdB736d13CE851Ee81ac2109DF37EBAb8Ce525C42',
        serviceRegistryName: 'AaveV3Payback',
        history: [],
        constructorArgs: ['address:ServiceRegistry'],
      },
      AaveV3SetEMode: {
        name: 'AaveV3SetEMode',
        deploy: false,
        address: '0xd4DB3799DEe98Fe752d952Ba6F84Bb99Af829920',
        serviceRegistryName: 'AaveV3SetEMode',
        history: [],
        constructorArgs: ['address:ServiceRegistry'],
      },
    },
  },
  common: {
    GnosisSafe: {
      name: 'GnosisSafe',
      address: '0x41A92d82D70005B55070dB7138b21d7c28F27CC0',
    },
    WETH: {
      name: 'WETH',
      address: '0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2',
      serviceRegistryName: CONTRACT_NAMES.common.WETH,
    },
    ETH: {
      name: 'ETH',
      address: '0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2',
    },
    STETH: {
      name: 'STETH',
      address: '0xae7ab96520de3a18e5e111b5eaab095312d7fe84',
      serviceRegistryName: CONTRACT_NAMES.common.STETH,
    },
    WSTETH: {
      name: 'WSTETH',
      address: '0x7f39c581f595b53c5cb19bd0b3f8da6c935e2ca0',
      serviceRegistryName: CONTRACT_NAMES.common.WSTETH,
    },
    USDC: {
      name: 'USDC',
      address: '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48',
      serviceRegistryName: CONTRACT_NAMES.common.USDC,
    },
    USDT: {
      name: 'USDT',
      address: constants.AddressZero,
    },
    DAI: {
      name: 'DAI',
      address: '0x6B175474E89094C44Da98b954EedeAC495271d0F',
      serviceRegistryName: CONTRACT_NAMES.common.DAI,
    },
    WBTC: {
      name: 'WBTC',
      address: '0x2260fac5e5542a773aa44fbcfedf7c193bc2c599',
      serviceRegistryName: CONTRACT_NAMES.common.WBTC,
    },
    LINK: {
      name: 'WBTC',
      address: constants.AddressZero,
    },
    UniswapRouterV3: {
      name: 'UniswapRouterV3',
      address: '0xe592427a0aece92de3edee1f18e0157c05861564',
      serviceRegistryName: CONTRACT_NAMES.common.UNISWAP_ROUTER,
    },
    BalancerVault: {
      name: 'BalancerVault',
      address: '0xBA12222222228d8Ba445958a75a0704d566BF2C8',
      serviceRegistryName: CONTRACT_NAMES.common.BALANCER_VAULT,
    },
    OneInchAggregator: {
      name: 'OneInchAggregator',
      address: '0x1111111254fb6c44bac0bed2854e76f90643097d',
      serviceRegistryName: CONTRACT_NAMES.common.ONE_INCH_AGGREGATOR,
    },
    AuthorizedCaller: {
      name: 'AuthorizedCaller',
      address: '0x85f9b7408afE6CEb5E46223451f5d4b832B522dc',
    },
    FeeRecipient: {
      name: 'FeeRecipient',
      address: '0xC7b548AD9Cf38721810246C079b2d8083aba8909',
    },
    ChainlinkEthUsdPriceFeed: {
      name: 'ChainlinkEthUsdPriceFeed',
      address: constants.AddressZero,
    },
  },
  aave: {
    v3: {
      AaveOracle: {
        name: 'AaveOracle',
        address: constants.AddressZero,
      },
      Pool: {
        name: 'Pool',
        address: constants.AddressZero,
        serviceRegistryName: CONTRACT_NAMES.aave.v3.AAVE_POOL,
      },
      AaveProtocolDataProvider: {
        name: 'AaveProtocolDataProvider',
        address: constants.AddressZero,
      },
    },
  },
  maker: {
    FlashMintModule: {
      name: 'FlashMintModule',
      address: '0x60744434d6339a6B27d73d9Eda62b6F66a0a04FA',
      serviceRegistryName: CONTRACT_NAMES.maker.FLASH_MINT_MODULE,
    },
    Chainlog: {
      name: 'Chainlog',
      address: constants.AddressZero,
    },
    CdpManager: {
      name: 'CdpManager',
      address: constants.AddressZero,
    },
    GetCdps: {
      name: 'CdpManager',
      address: constants.AddressZero,
    },
    Jug: {
      name: 'Jug',
      address: constants.AddressZero,
    },
    JoinDAI: {
      name: 'JoinDAI',
      address: constants.AddressZero,
    },
    JoinETH_A: {
      name: 'JoinETH_A',
      address: constants.AddressZero,
    },
    PipWETH: {
      name: 'PipWETH',
      address: constants.AddressZero,
    },
    PipLINK: {
      name: 'PipLINK',
      address: constants.AddressZero,
    },
  },
}
