"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.optimismConfig = exports.mainnetConfig = exports.localExtendConfig = exports.goerliConfig = void 0;
var goerli_conf_1 = require("./goerli.conf");
Object.defineProperty(exports, "goerliConfig", { enumerable: true, get: function () { return goerli_conf_1.goerliConfig; } });
var local_extend_conf_1 = require("./local-extend.conf");
Object.defineProperty(exports, "localExtendConfig", { enumerable: true, get: function () { return local_extend_conf_1.localExtendConfig; } });
var mainnet_conf_1 = require("./mainnet.conf");
Object.defineProperty(exports, "mainnetConfig", { enumerable: true, get: function () { return mainnet_conf_1.mainnetConfig; } });
var optimism_conf_1 = require("./optimism.conf");
Object.defineProperty(exports, "optimismConfig", { enumerable: true, get: function () { return optimism_conf_1.optimismConfig; } });
