import { SystemConfig } from '@dma-deployments/types/deployment-config'
import { constants } from 'ethers'

export const config: SystemConfig = {
  mpa: {
    core: {
      ServiceRegistry: {
        name: 'ServiceRegistry',
        deploy: false,
        address: '0x063E4242CD7C2421f67e21D7297c74bbDFEF7b0E',
        history: ['0xf22F17B1D2354B4F4F52e4d164e4eB5e1f0A6Ba6'],
        constructorArgs: [0],
      },
      OperationExecutor: {
        name: 'OperationExecutor',
        deploy: false,
        address: '0xFDFf46fF5752CE2A4CAbAAf5a2cFF3744E1D09de',
        serviceRegistryName: 'OperationExecutor_2',
        history: ['0x5AB3e51608cEa26090445CA89bc91628C8bB99f9'],
        constructorArgs: ['address:ServiceRegistry'],
      },
      OperationStorage: {
        name: 'OperationStorage',
        deploy: false,
        address: '0x6d3af85e27686FfF7686b2FAe174b0a7d8c95e16',
        serviceRegistryName: 'OperationStorage_2',
        history: ['0xd4FEaf1023CD6998053a1eb02460000980Cc908f'],
        constructorArgs: ['address:ServiceRegistry', 'address:OperationExecutor'],
      },
      OperationsRegistry: {
        name: 'OperationsRegistry',
        deploy: false,
        address: '0x3Dd262181BA245184a903CD8B77E23417f815669',
        serviceRegistryName: 'OperationsRegistry_2',
        history: ['0x392ACeBea829373A3eFDc0dA80a16003106d8f6E'],
        constructorArgs: [],
      },
      DSProxyFactory: {
        name: 'DSProxyFactory',
        deploy: false,
        address: '0x93dFeCd48491eCc6F6EC82B0fEE1Cba9eF9C941A',
        serviceRegistryName: 'DSProxyFactory',
        history: [],
        constructorArgs: [],
      },
      DSProxyRegistry: {
        name: 'DSProxyRegistry',
        deploy: false,
        address: '0x4EcDc277484D71A3BD15f36C858aEc2C56803869',
        serviceRegistryName: 'DSProxyRegistry',
        history: [],
        constructorArgs: ['address:DSProxyFactory'],
      },
      DSGuardFactory: {
        name: 'DSGuardFactory',
        deploy: false,
        address: '0x7bBe5f9C95E2994C420B3Af063e74e5F87b2A3B5',
        serviceRegistryName: 'DSGuardFactory',
        history: [],
        constructorArgs: [],
      },
      AccountGuard: {
        name: 'AccountGuard',
        deploy: false,
        address: '0x916411367fC2f0dc828790eA03CF317eC74E24E4',
        serviceRegistryName: 'AccountGuard',
        history: ['0x63059cC2533344B65372983D4B6258b2cbbBF0Da'],
        constructorArgs: [],
      },
      AccountFactory: {
        name: 'AccountFactory',
        deploy: false,
        address: '0xaaf64927BaFe68E389DE3627AA6b52D81bdA2323',
        serviceRegistryName: 'AccountFactory',
        history: ['0xE166a06809FD35Cece10df9Cace87BbDB9a48F66'],
        constructorArgs: ['address:AccountGuard'],
      },
      Swap: {
        name: 'Swap',
        deploy: false,
        address: '0x4De3CA09e803969408f83F453416b3e2D70C12Fe',
        serviceRegistryName: 'Swap',
        history: [],
        constructorArgs: [
          '0x85f9b7408afE6CEb5E46223451f5d4b832B522dc',
          '0xC7b548AD9Cf38721810246C079b2d8083aba8909',
          20,
          'address:ServiceRegistry',
        ],
      },
    },
    actions: {
      PositionCreated: {
        name: 'PositionCreated',
        deploy: false,
        address: '0x8061c24823094E51e57A4a5cF8bEd3CCf09d316F',
        serviceRegistryName: 'PositionCreated',
        history: ['0xE7aA0939F0cFF45162A22751CbE0009c689EA256'],
        constructorArgs: [],
      },
      SwapAction: {
        name: 'SwapAction',
        deploy: false,
        address: '0x398105CD43115b54A0EFE0b210D99c596e4571A7',
        serviceRegistryName: 'SwapAction_3',
        history: ['0x55D4d311Cd9B2dD5693FB51f06DbE50B9Da84D13'],
        constructorArgs: ['address:ServiceRegistry'],
      },
      TakeFlashloan: {
        name: 'TakeFlashloan',
        deploy: false,
        address: '0x080bB3a23098D71a4e8fc5dE8f1Cbb83553BBc57',
        serviceRegistryName: 'TakeFlashloan_3',
        history: ['0x53958191c3077eDe3Ca90Eb840283df063FC1be3'],
        constructorArgs: [
          'address:ServiceRegistry',
          '0xda10009cbd5d07dd0cecc66161fc93d7c9000da1',
          'address:DSGuardFactory',
        ],
      },
      SetApproval: {
        name: 'SetApproval',
        deploy: false,
        address: '0x18ca8bE41D32727383bC0F98705f7662ed0B7E28',
        serviceRegistryName: 'SetApproval_3',
        history: ['0x983EFCA0Fd5F9B03f75BbBD41F4BeD3eC20c96d8'],
        constructorArgs: ['address:ServiceRegistry'],
      },
      PullToken: {
        name: 'PullToken',
        deploy: false,
        address: '0x414958801DC53E840501f507D7A0FEBE55806200',
        serviceRegistryName: 'PullToken_3',
        history: ['0xFAf9D0B7B92e8B281CaF10b42970179B45CA6412'],
        constructorArgs: [],
      },
      SendToken: {
        name: 'SendToken',
        deploy: false,
        address: '0xAa4C55A8dd5b0e923056676D544FC20bb5D5e3A3',
        serviceRegistryName: 'SendToken_4',
        history: ['0xeB54C366512c4d59A222A251ea7316568859E08C'],
        constructorArgs: ['address:ServiceRegistry'],
      },
      WrapEth: {
        name: 'WrapEth',
        deploy: false,
        address: '0xaAF5aBF888d6633cAB2bb04E46EBb2FD3ba98B14',
        serviceRegistryName: 'WrapEth_3',
        history: ['0x43C9a445fCf3bc3d1483c0b90DC0346249c0D84C'],
        constructorArgs: ['address:ServiceRegistry'],
      },
      UnwrapEth: {
        name: 'UnwrapEth',
        deploy: false,
        address: '0xF8C44FDB83bC89FE3db2FeAE98e2732FDa469699',
        serviceRegistryName: 'UnwrapEth_3',
        history: ['0x7E7EB65A93441a2D2Bf0941216b4c1116B554d85'],
        constructorArgs: ['address:ServiceRegistry'],
      },
      ReturnFunds: {
        name: 'ReturnFunds',
        deploy: false,
        address: '0x0eD12441616ca97F5729Fff519F5e8d13d8De15F',
        serviceRegistryName: 'ReturnFunds_3',
        history: ['0xAC0B1652388Ea425884e6b60e2eD30155f43D50b'],
        constructorArgs: [],
      },
      AaveV3Borrow: {
        name: 'AaveV3Borrow',
        deploy: false,
        address: '0x330B1b23dbF728841AF12e6478CeBb9d51ab6f90',
        serviceRegistryName: 'AaveV3Borrow',
        history: ['0x645325494A37d35cf6baFc82C3e6bcE4473F2685'],
        constructorArgs: ['address:ServiceRegistry'],
      },
      AaveV3Withdraw: {
        name: 'AaveV3Withdraw',
        deploy: false,
        address: '0x98Ee526EdF6c9c3cfa1369a5D24bC2c6c278bB19',
        serviceRegistryName: 'AaveV3Withdraw',
        history: ['0xb3f0C5E4012aF22359c9Ab233DABd80cD81F5ec5'],
        constructorArgs: ['address:ServiceRegistry'],
      },
      AaveV3Deposit: {
        name: 'AaveV3Deposit',
        deploy: false,
        address: '0x22E4CeE555C44df56ac7B85033cdE54B7439817c',
        serviceRegistryName: 'AaveV3Deposit',
        history: ['0x2006d4e76A398c78964F7e311BFd7Ccb149EaFE2'],
        constructorArgs: ['address:ServiceRegistry'],
      },
      AaveV3Payback: {
        name: 'AaveV3Payback',
        deploy: false,
        address: '0x3f91613F0c7f1f5940c324FfeF07632DD5793680',
        serviceRegistryName: 'AaveV3Payback',
        history: ['0xA0Cb87300aB07D00468704cD8f016F8dE47D8E0A'],
        constructorArgs: ['address:ServiceRegistry'],
      },
      AaveV3SetEMode: {
        name: 'AaveV3SetEMode',
        deploy: false,
        address: '0x36a9ED9B00ECC380C4e559B80a1857C65353ce7e',
        serviceRegistryName: 'AaveV3SetEMode',
        history: [],
        constructorArgs: ['address:ServiceRegistry'],
      },
    },
  },
  common: {
    GnosisSafe: {
      name: 'GnosisSafe',
      address: constants.AddressZero,
    },
    UniswapRouterV3: {
      name: 'UniswapRouterV3',
      address: '0xE592427A0AEce92De3Edee1F18E0157C05861564',
      serviceRegistryName: 'UniswapRouter',
    },
    BalancerVault: {
      name: 'BalancerVault',
      address: '0xBA12222222228d8Ba445958a75a0704d566BF2C8',
      serviceRegistryName: 'BalancerVault',
    },
    FeeRecipient: {
      name: 'FeeRecipient',
      address: '0xC7b548AD9Cf38721810246C079b2d8083aba8909',
    },
    AuthorizedCaller: {
      name: 'AuthorizedCaller',
      address: '0x85f9b7408afE6CEb5E46223451f5d4b832B522dc',
    },
    OneInchAggregator: {
      name: 'OneInchAggregator',
      address: '0x1111111254EEB25477B68fb85Ed929f73A960582',
      serviceRegistryName: 'OneInchAggregator',
    },
    MerkleRedeemer: {
      name: 'MerkleRedeemer',
      address: constants.AddressZero,
    },
    DssCharter: {
      name: 'DssCharter',
      address: constants.AddressZero,
    },
    DssProxyActions: {
      name: 'DssProxyActions',
      address: constants.AddressZero,
    },
    DssProxyActionsCharter: {
      name: 'DssProxyActionsCharter',
      address: constants.AddressZero,
    },
    DssMultiplyProxyActions: {
      name: 'DssMultiplyProxyActions',
      address: constants.AddressZero,
    },
    DssCropper: {
      name: 'DssCropper',
      address: constants.AddressZero,
    },
    DssProxyActionsCropjoin: {
      name: 'DssProxyActionsCropjoin',
      address: constants.AddressZero,
    },
    DssProxyActionsDsr: {
      name: 'DssProxyActionsDsr',
      address: constants.AddressZero,
    },
    Otc: {
      name: 'Otc',
      address: constants.AddressZero,
    },
    OtcSupportMethods: {
      name: 'OtcSupportMethods',
      address: constants.AddressZero,
    },
    ServiceRegistry: {
      name: 'ServiceRegistry',
      address: constants.AddressZero,
    },
    GuniProxyActions: {
      name: 'GuniProxyActions',
      address: constants.AddressZero,
    },
    GuniResolver: {
      name: 'GuniResolver',
      address: constants.AddressZero,
    },
    GuniRouter: {
      name: 'GuniRouter',
      address: constants.AddressZero,
    },
    CdpRegistry: {
      name: 'CdpRegistry',
      address: constants.AddressZero,
    },
    DefaultExchange: {
      name: 'DefaultExchange',
      address: constants.AddressZero,
    },
    NoFeesExchange: {
      name: 'NoFeesExchange',
      address: constants.AddressZero,
    },
    LowerFeesExchange: {
      name: 'LowerFeesExchange',
      address: constants.AddressZero,
    },
    LidoCrvLiquidityFarmingReward: {
      name: 'LidoCrvLiquidityFarmingReward',
      address: constants.AddressZero,
    },
    ChainlinkPriceOracle_USDCUSD: {
      name: 'ChainlinkPriceOracle_USDCUSD',
      address: constants.AddressZero,
    },
    ChainlinkPriceOracle_ETHUSD: {
      name: 'ChainlinkPriceOracle_ETHUSD',
      address: '0x13e3ee699d1909e989722e753853ae30b17e08c5',
    },
    ADAI: { name: 'ADAI', address: constants.AddressZero },
    AAVE: { name: 'AAVE', address: constants.AddressZero },
    BAL: { name: 'BAL', address: constants.AddressZero },
    BAT: { name: 'BAT', address: constants.AddressZero },
    COMP: { name: 'COMP', address: constants.AddressZero },
    CRVV1ETHSTETH: { name: 'CRVV1ETHSTETH', address: constants.AddressZero },
    DAI: {
      name: 'DAI',
      address: constants.AddressZero,
      serviceRegistryName: 'DAI',
    },
    ETH: { name: 'ETH', address: constants.AddressZero },
    GNO: { name: 'GNO', address: constants.AddressZero },
    GUNIV3DAIUSDC1: {
      name: 'GUNIV3DAIUSDC1',
      address: constants.AddressZero,
    },
    GUNIV3DAIUSDC2: {
      name: 'GUNIV3DAIUSDC2',
      address: constants.AddressZero,
    },
    GUSD: { name: 'GUSD', address: constants.AddressZero },
    KNC: { name: 'KNC', address: constants.AddressZero },
    LDO: { name: 'LDO', address: constants.AddressZero },
    LINK: { name: 'LINK', address: constants.AddressZero },
    LRC: { name: 'LRC', address: constants.AddressZero },
    MANA: { name: 'MANA', address: constants.AddressZero },
    MATIC: { name: 'MATIC', address: constants.AddressZero },
    PAX: { name: 'PAX', address: constants.AddressZero },
    PAXUSD: { name: 'PAXUSD', address: constants.AddressZero },
    RENBTC: { name: 'RENBTC', address: constants.AddressZero },
    RETH: { name: 'RETH', address: constants.AddressZero },
    RWA001: { name: 'RWA001', address: constants.AddressZero },
    RWA002: { name: 'RWA002', address: constants.AddressZero },
    RWA003: { name: 'RWA003', address: constants.AddressZero },
    RWA004: { name: 'RWA004', address: constants.AddressZero },
    RWA005: { name: 'RWA005', address: constants.AddressZero },
    RWA006: { name: 'RWA006', address: constants.AddressZero },
    STETH: { name: 'STETH', address: constants.AddressZero },
    TUSD: { name: 'TUSD', address: constants.AddressZero },
    UNI: { name: 'UNI', address: constants.AddressZero },
    UNIV2AAVEETH: { name: 'UNIV2AAVEETH', address: constants.AddressZero },
    UNIV2DAIETH: { name: 'UNIV2DAIETH', address: constants.AddressZero },
    UNIV2DAIUSDC: { name: 'UNIV2DAIUSDC', address: constants.AddressZero },
    UNIV2DAIUSDT: { name: 'UNIV2DAIUSDT', address: constants.AddressZero },
    UNIV2ETHUSDT: { name: 'UNIV2ETHUSDT', address: constants.AddressZero },
    UNIV2LINKETH: { name: 'UNIV2LINKETH', address: constants.AddressZero },
    UNIV2UNIETH: { name: 'UNIV2UNIETH', address: constants.AddressZero },
    UNIV2USDCETH: { name: 'UNIV2USDCETH', address: constants.AddressZero },
    UNIV2WBTCDAI: { name: 'UNIV2WBTCDAI', address: constants.AddressZero },
    UNIV2WBTCETH: { name: 'UNIV2WBTCETH', address: constants.AddressZero },
    USDC: {
      name: 'USDC',
      address: constants.AddressZero,
      serviceRegistryName: 'USDC',
    },
    USDT: { name: 'USDT', address: constants.AddressZero },
    WBTC: {
      name: 'WBTC',
      address: constants.AddressZero,
      serviceRegistryName: 'WBTC',
    },
    WETH: {
      name: 'WETH',
      address: constants.AddressZero,
      serviceRegistryName: 'WETH',
    },
    WSTETH: {
      name: 'WSTETH',
      address: constants.AddressZero,
      serviceRegistryName: 'WSTETH',
    },
    YFI: { name: 'YFI', address: constants.AddressZero },
    ZRX: { name: 'ZRX', address: constants.AddressZero },
  },
  aave: {
    v3: {
      AaveOracle: {
        name: 'AaveOracle',
        address: '0xD81eb3728a631871a7eBBaD631b5f424909f0c77',
      },
      Pool: {
        name: 'Pool',
        address: '0x794a61358D6845594F94dc1DB02A252b5b4814aD',
        serviceRegistryName: 'AavePool',
      },
      AaveProtocolDataProvider: {
        name: 'AaveProtocolDataProvider',
        address: '0x69FA688f1Dc47d4B5d8029D5a35FB7a548310654',
      },
    },
  },
  maker: {
    FlashMintModule: {
      name: 'FlashMintModule',
      address: constants.AddressZero,
    },
    Chainlog: {
      name: 'Chainlog',
      address: constants.AddressZero,
    },
    CdpManager: {
      name: 'CdpManager',
      address: constants.AddressZero,
    },
    GetCdps: {
      name: 'GetCdps',
      address: constants.AddressZero,
    },
    Jug: {
      name: 'Jug',
      address: constants.AddressZero,
    },
    Pot: {
      name: 'Pot',
      address: constants.AddressZero,
    },
    End: {
      name: 'End',
      address: constants.AddressZero,
    },
    Spot: {
      name: 'Spot',
      address: constants.AddressZero,
    },
    Dog: {
      name: 'Dog',
      address: constants.AddressZero,
    },
    Vat: {
      name: 'Vat',
      address: constants.AddressZero,
    },
    McdGov: {
      name: 'McdGov',
      address: constants.AddressZero,
    },
    JoinDAI: {
      name: 'JoinDAI',
      address: constants.AddressZero,
    },
    JoinETH_A: {
      name: 'JoinETH_A',
      address: constants.AddressZero,
    },
    PipWETH: {
      name: 'PipWETH',
      address: constants.AddressZero,
    },
    PipLINK: {
      name: 'PipLINK',
      address: constants.AddressZero,
    },
  },
  automation: {
    AutomationBot: {
      name: 'AutomationBot',
      address: constants.AddressZero,
    },
    AutomationBotV2: {
      name: 'AutomationBotV2',
      address: constants.AddressZero,
    },
    AutomationBotAggregator: {
      name: 'AutomationBotAggregator',
      address: constants.AddressZero,
    },
  },
  ajna: {
    AjnaPoolInfo: {
      name: 'AjnaPoolInfo',
      address: constants.AddressZero,
    },
    AjnaProxyActions: {
      name: 'AjnaProxyActions',
      address: constants.AddressZero,
    },
    AjnaPoolPairs_WBTCUSDC: {
      name: 'AjnaPoolPairs_WBTCUSDC',
      address: constants.AddressZero,
    },
    AjnaPoolPairs_ETHUSDC: {
      name: 'AjnaPoolPairs_ETHUSDC',
      address: constants.AddressZero,
    },
    AjnaRewardsManager: {
      name: 'AjnaRewardsManager',
      address: constants.AddressZero,
    },
    AjnaRewardsClaimer: {
      name: 'AjnaRewardsClaimer',
      address: constants.AddressZero,
    },
  },
}
