/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  DummyAction,
  DummyActionInterface,
} from "../../../../system/contracts/test/DummyAction";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_registry",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "",
        type: "bytes",
      },
      {
        internalType: "uint8[]",
        name: "",
        type: "uint8[]",
      },
    ],
    name: "execute",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
] as const;

export class DummyAction__factory {
  static readonly abi = _abi;
  static createInterface(): DummyActionInterface {
    return new Interface(_abi) as DummyActionInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): DummyAction {
    return new Contract(address, _abi, runner) as unknown as DummyAction;
  }
}
