/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  SuicideBomb,
  SuicideBombInterface,
} from "../../../../system/contracts/test/SuicideBomb";

const _abi = [
  {
    stateMutability: "payable",
    type: "fallback",
  },
] as const;

export class SuicideBomb__factory {
  static readonly abi = _abi;
  static createInterface(): SuicideBombInterface {
    return new utils.Interface(_abi) as SuicideBombInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): SuicideBomb {
    return new Contract(address, _abi, signerOrProvider) as SuicideBomb;
  }
}
