/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  SuicideBomb,
  SuicideBombInterface,
} from "../../../../system/contracts/test/SuicideBomb";

const _abi = [
  {
    stateMutability: "payable",
    type: "fallback",
  },
] as const;

export class SuicideBomb__factory {
  static readonly abi = _abi;
  static createInterface(): SuicideBombInterface {
    return new Interface(_abi) as SuicideBombInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): SuicideBomb {
    return new Contract(address, _abi, runner) as unknown as SuicideBomb;
  }
}
