/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IWETHGateway,
  IWETHGatewayInterface,
} from "../../../../../system/contracts/interfaces/aave/IWETHGateway";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "lendingPool",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "interestRateMode",
        type: "uint256",
      },
      {
        internalType: "uint16",
        name: "referralCode",
        type: "uint16",
      },
    ],
    name: "borrowETH",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IWETHGateway__factory {
  static readonly abi = _abi;
  static createInterface(): IWETHGatewayInterface {
    return new utils.Interface(_abi) as IWETHGatewayInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IWETHGateway {
    return new Contract(address, _abi, signerOrProvider) as IWETHGateway;
  }
}
