import { ADDRESSES, CONTRACT_NAMES } from '@oasisdex/oasis-actions'

export const config = {
  mpa: {
    core: {
      ServiceRegistry: {
        name: 'ServiceRegistry',
        deploy: true,
        address: '',
        serviceRegistryName: '',
        history: [],
        constructorArgs: [0],
      },
      OperationExecutor: {
        name: 'OperationExecutor',
        deploy: true,
        address: '',
        serviceRegistryName: 'OperationExecutor_2',
        history: [],
        constructorArgs: ['address:ServiceRegistry'],
      },
      OperationStorage: {
        name: 'OperationStorage',
        deploy: true,
        address: '',
        serviceRegistryName: 'OperationStorage_2',
        history: [],
        constructorArgs: ['address:ServiceRegistry', 'address:OperationExecutor'],
      },
      OperationRegistry: {
        name: 'OperationsRegistry',
        deploy: true,
        address: '',
        serviceRegistryName: 'OperationsRegistry_2',
        history: [],
        constructorArgs: [],
      },
      AccountGuard: {
        name: 'AccountGuard',
        deploy: true,
        address: '',
        serviceRegistryName: '',
        history: [],
        constructorArgs: [],
      },
      AccountFactory: {
        name: 'AccountFactory',
        deploy: true,
        address: '',
        serviceRegistryName: '',
        history: [],
        constructorArgs: ['address:AccountGuard'],
      },
      ChainLogView: {
        name: 'ChainLogView',
        deploy: true,
        address: '',
        serviceRegistryName: 'ChainLogView',
        history: [],
        constructorArgs: ['0xdA0Ab1e0017DEbCd72Be8599041a2aa3bA7e740F'],
      },
    },
    actions: {
      PositionCreated: {
        name: 'PositionCreated',
        deploy: true,
        address: '',
        serviceRegistryName: 'PositionCreated',
        history: [],
        constructorArgs: [],
      },
      SwapAction: {
        name: 'SwapAction',
        deploy: true,
        address: '',
        serviceRegistryName: 'SwapAction_3',
        history: [],
        constructorArgs: ['address:ServiceRegistry'],
      },
      TakeFlashloan: {
        name: 'TakeFlashloan',
        deploy: true,
        address: '',
        serviceRegistryName: 'TakeFlashloan_3',
        history: [],
        constructorArgs: [
          'address:ServiceRegistry',
          '0xda10009cbd5d07dd0cecc66161fc93d7c9000da1',
          '0xc19d0F1E2b38AA283E226Ca4044766A43aA7B02b',
        ],
      },
      SetApproval: {
        name: 'SetApproval',
        deploy: true,
        address: '',
        serviceRegistryName: 'SetApproval_3',
        history: [],
        constructorArgs: ['address:ServiceRegistry'],
      },
      PullToken: {
        name: 'PullToken',
        deploy: true,
        address: '',
        serviceRegistryName: 'PullToken_3',
        history: [],
        constructorArgs: [],
      },
      SendToken: {
        name: 'SendToken',
        deploy: true,
        address: '',
        serviceRegistryName: 'SendToken_4',
        history: [],
        constructorArgs: ['address:ServiceRegistry'],
      },
      WrapEth: {
        name: 'WrapEth',
        deploy: true,
        address: '',
        serviceRegistryName: 'WrapEth_3',
        history: [],
        constructorArgs: ['address:ServiceRegistry'],
      },
      UnwrapEth: {
        name: 'UnwrapEth',
        deploy: true,
        address: '',
        serviceRegistryName: 'UnwrapEth_3',
        history: [],
        constructorArgs: ['address:ServiceRegistry'],
      },
      ReturnFunds: {
        name: 'ReturnFunds',
        deploy: true,
        address: '',
        serviceRegistryName: 'ReturnFunds_3',
        history: [],
        constructorArgs: [],
      },
      AaveV3Borrow: {
        name: 'AaveV3Borrow',
        deploy: true,
        address: '',
        serviceRegistryName: 'AaveV3Borrow',
        history: [],
        constructorArgs: ['address:ServiceRegistry'],
      },
      AaveV3Withdraw: {
        name: 'AaveV3Withdraw',
        deploy: true,
        address: '',
        serviceRegistryName: 'AaveV3Withdraw',
        history: [],
        constructorArgs: ['address:ServiceRegistry'],
      },
      AaveV3Deposit: {
        name: 'AaveV3Deposit',
        deploy: true,
        address: '',
        serviceRegistryName: 'AaveV3Deposit',
        history: [],
        constructorArgs: ['address:ServiceRegistry'],
      },
      AaveV3Payback: {
        name: 'AaveV3Payback',
        deploy: true,
        address: '',
        serviceRegistryName: 'AaveV3Payback',
        history: [],
        constructorArgs: ['address:ServiceRegistry'],
      },
      AaveV3SetEMode: {
        name: 'AaveV3SetEMode',
        deploy: true,
        address: '',
        serviceRegistryName: 'AaveV3SetEMode',
        history: [],
        constructorArgs: ['address:ServiceRegistry'],
      },
    },
  },
  common: {
    WETH: {
      name: 'WETH',
      address: '0x4200000000000000000000000000000000000006',
      serviceRegistryName: CONTRACT_NAMES.common.WETH,
    },
    ETH: {
      name: 'ETH',
      address: '0x4200000000000000000000000000000000000006',
    },
    USDC: {
      name: 'USDC',
      address: '0x7F5c764cBc14f9669B88837ca1490cCa17c31607',
      serviceRegistryName: CONTRACT_NAMES.common.USDC,
    },
    DAI: {
      name: 'DAI',
      address: '0xDA10009cBd5D07dd0CeCc66161FC93D7c9000da1',
      serviceRegistryName: CONTRACT_NAMES.common.DAI,
    },
    WSTETH: {
      name: 'WSTETH',
      address: ADDRESSES.optimism.WSTETH,
    },
    WBTC: {
      name: 'WBTC',
      address: ADDRESSES.optimism.WBTC,
    },
    UniswapRouterV3: {
      name: 'UniswapRouterV3',
      address: '0xE592427A0AEce92De3Edee1F18E0157C05861564',
      serviceRegistryName: CONTRACT_NAMES.common.UNISWAP_ROUTER,
    },
    BalancerVault: {
      name: 'BalancerVault',
      address: '0xBA12222222228d8Ba445958a75a0704d566BF2C8',
      serviceRegistryName: CONTRACT_NAMES.common.BALANCER_VAULT,
    },
    FeeRecipient: {
      name: 'FeeRecipient',
      address: '0xC7b548AD9Cf38721810246C079b2d8083aba8909',
    },
    DsProxyRegistry: {
      name: 'DsProxyRegistry',
      address: '0x283Cc5C26e53D66ed2Ea252D986F094B37E6e895',
    },
    OneInchAggregator: {
      name: 'OneInchAggregator',
      address: '0x1111111254EEB25477B68fb85Ed929f73A960582',
      serviceRegistryName: CONTRACT_NAMES.common.ONE_INCH_AGGREGATOR,
    },
    ChainlinkEthUsdPriceFeed: {
      name: 'ChainlinkEthUsdPriceFeed',
      address: ADDRESSES.optimism.chainlinkEthUsdPriceFeed,
    },
  },
  aave: {
    v3: {
      AaveOracle: {
        name: 'AaveOracle',
        address: ADDRESSES.optimism.aave.v3.AaveOracle,
      },
      Pool: {
        name: 'Pool',
        address: ADDRESSES.optimism.aave.v3.Pool,
        serviceRegistryName: CONTRACT_NAMES.aave.v3.AAVE_POOL,
      },
      AaveProtocolDataProvider: {
        name: 'AaveProtocolDataProvider',
        address: ADDRESSES.optimism.aave.v3.PoolDataProvider,
      },
    },
  },
}
