/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IERC721PoolLenderActions,
  IERC721PoolLenderActionsInterface,
} from "../../../../../../../system/contracts/ajna/interfaces/pool/erc721/IERC721PoolLenderActions";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256[]",
        name: "tokenIds_",
        type: "uint256[]",
      },
      {
        internalType: "uint256",
        name: "index_",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "expiry_",
        type: "uint256",
      },
    ],
    name: "addCollateral",
    outputs: [
      {
        internalType: "uint256",
        name: "bucketLP_",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256[]",
        name: "removalIndexes_",
        type: "uint256[]",
      },
      {
        internalType: "uint256",
        name: "noOfNFTsToRemove_",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "toIndex_",
        type: "uint256",
      },
    ],
    name: "mergeOrRemoveCollateral",
    outputs: [
      {
        internalType: "uint256",
        name: "collateralMerged_",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "bucketLP_",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IERC721PoolLenderActions__factory {
  static readonly abi = _abi;
  static createInterface(): IERC721PoolLenderActionsInterface {
    return new Interface(_abi) as IERC721PoolLenderActionsInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IERC721PoolLenderActions {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IERC721PoolLenderActions;
  }
}
