/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IRewardsManagerDerivedState,
  IRewardsManagerDerivedStateInterface,
} from "../../../../../../system/contracts/ajna/interfaces/rewards/IRewardsManagerDerivedState";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId_",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "epochToClaim_",
        type: "uint256",
      },
    ],
    name: "calculateRewards",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IRewardsManagerDerivedState__factory {
  static readonly abi = _abi;
  static createInterface(): IRewardsManagerDerivedStateInterface {
    return new utils.Interface(_abi) as IRewardsManagerDerivedStateInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IRewardsManagerDerivedState {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IRewardsManagerDerivedState;
  }
}
