/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IPoolTakerActions,
  IPoolTakerActionsInterface,
} from "../../../../../../../system/contracts/ajna/interfaces/pool/commons/IPoolTakerActions";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "borrowerAddress_",
        type: "address",
      },
      {
        internalType: "bool",
        name: "depositTake_",
        type: "bool",
      },
      {
        internalType: "uint256",
        name: "index_",
        type: "uint256",
      },
    ],
    name: "bucketTake",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "borrowerAddress_",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "maxAmount_",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "callee_",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "data_",
        type: "bytes",
      },
    ],
    name: "take",
    outputs: [
      {
        internalType: "uint256",
        name: "collateralTaken_",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "maxAmount_",
        type: "uint256",
      },
    ],
    name: "takeReserves",
    outputs: [
      {
        internalType: "uint256",
        name: "amount_",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IPoolTakerActions__factory {
  static readonly abi = _abi;
  static createInterface(): IPoolTakerActionsInterface {
    return new utils.Interface(_abi) as IPoolTakerActionsInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IPoolTakerActions {
    return new Contract(address, _abi, signerOrProvider) as IPoolTakerActions;
  }
}
