/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IPoolKickerActions,
  IPoolKickerActionsInterface,
} from "../../../../../../../system/contracts/ajna/interfaces/pool/commons/IPoolKickerActions";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "borrower_",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "npLimitIndex_",
        type: "uint256",
      },
    ],
    name: "kick",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "kickReserveAuction",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "index_",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "npLimitIndex_",
        type: "uint256",
      },
    ],
    name: "lenderKick",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "recipient_",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "maxAmount_",
        type: "uint256",
      },
    ],
    name: "withdrawBonds",
    outputs: [
      {
        internalType: "uint256",
        name: "withdrawnAmount_",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IPoolKickerActions__factory {
  static readonly abi = _abi;
  static createInterface(): IPoolKickerActionsInterface {
    return new utils.Interface(_abi) as IPoolKickerActionsInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IPoolKickerActions {
    return new Contract(address, _abi, signerOrProvider) as IPoolKickerActions;
  }
}
