/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IPoolBorrowerActions,
  IPoolBorrowerActionsInterface,
} from "../../../../../../../system/contracts/ajna/interfaces/pool/commons/IPoolBorrowerActions";

const _abi = [
  {
    inputs: [],
    name: "stampLoan",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IPoolBorrowerActions__factory {
  static readonly abi = _abi;
  static createInterface(): IPoolBorrowerActionsInterface {
    return new utils.Interface(_abi) as IPoolBorrowerActionsInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IPoolBorrowerActions {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IPoolBorrowerActions;
  }
}
