/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IPoolImmutables,
  IPoolImmutablesInterface,
} from "../../../../../../../system/contracts/ajna/interfaces/pool/commons/IPoolImmutables";

const _abi = [
  {
    inputs: [],
    name: "collateralAddress",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [],
    name: "poolType",
    outputs: [
      {
        internalType: "uint8",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [],
    name: "quoteTokenAddress",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [],
    name: "quoteTokenScale",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
] as const;

export class IPoolImmutables__factory {
  static readonly abi = _abi;
  static createInterface(): IPoolImmutablesInterface {
    return new utils.Interface(_abi) as IPoolImmutablesInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IPoolImmutables {
    return new Contract(address, _abi, signerOrProvider) as IPoolImmutables;
  }
}
